services:
  claudecodebox:
    container_name: ClaudeCodeBox
    build:
      context: ./build-context
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    ports:
      - "${CCCR_SSH_PORT}:22"
      - "${CCCR_WEB_PORT}:8080"
    env_file:
      - ../../../secrets/CCBX_CLAUDE.env
    volumes:
      # Workspace mount (parent of repo directory)
      - ../../../:/workspace
      # Named volumes for persistence
      - claude-config:/home/claude/.claude
      - claude-cache:/home/claude/.cache
    networks:
      - claude-network
    restart: unless-stopped

volumes:
  claude-config:
    name: claude-config
  claude-cache:
    name: claude-cache

networks:
  claude-network:
    name: claude-network
    driver: bridge

