services:
  claudecodebox:
    container_name: ClaudeCodeBox
    build:
      context: ./build-context
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    ports:
      - "${CCCR_SSH_PORT}:22"
      - "${CCCR_WEB_PORT}:8080"
    env_file:
      - ../../../secrets/CCBX_CLAUDE.env
    volumes:
      # Workspace mount (parent of repo directory)
      - ../../../:/workspace
      # Auth config persisted in workspace (outside any git repo)
      # Path matches zccck_claude_config_dir in cccw_workbench.sh
      - ../../../.claude-config:/home/claude/.config
    networks:
      - claude-network
    restart: unless-stopped

networks:
  claude-network:
    name: claude-network
    driver: bridge

