#!/bin/bash
#
# Copyright 2026 Scale Invariant, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Brad Hyslop <bhyslop@scaleinvariant.org>
#
# RBRR Reset CLI - Pre-kindle entry point for Marshal reset operations
#
# This CLI deliberately skips regime kindle/enforce so that reset
# can produce a blank regime (the middle-product state before
# onboarding populates valid values).

set -euo pipefail

source "${BURD_BUK_DIR}/buc_command.sh"

######################################################################
# Command Functions

rbrr_reset() {
  buc_doc_brief "Reset RBRR repo regime to blank template for release qualification"
  buc_doc_shown || return 0

  local -r z_rbrr="${RBBC_rbrr_file}"
  test -n "${z_rbrr}" || buc_die "RBBC_rbrr_file is empty"

  bug_section "Marshal Reset"
  bug_t "  Target: ${z_rbrr}"
  bug_t "  All RBRR fields will be blanked."
  bug_t "  Credential files (RBRA/RBRO) are NOT touched."
  bug_e

  # Write blank-but-complete RBRR template
  # Every field present with empty value:
  #   - set -u survives (variables exist when sourced)
  #   - onboarding probes correctly detect unconfigured state
  #   - validation correctly rejects (empty values fail format checks)
  cat > "${z_rbrr}" <<'RBRR_TEMPLATE'
#!/bin/bash
# Recipe Bottle Repository Configuration - Blank Template
# Generated by rbw-MR Marshal Reset for release qualification.
# Run rbw-gPo (Payor Onboarding) to populate these fields.

RBRR_DNS_SERVER=

RBRR_IGNITE_MACHINE_NAME=
RBRR_DEPLOY_MACHINE_NAME=

# Reference directory containing specs for all vessels: relative to project root
RBRR_VESSEL_DIR=

# Depot configuration items
RBRR_DEPOT_PROJECT_ID=
RBRR_GCP_REGION=
RBRR_GAR_REPOSITORY=
RBRR_CBV2_CONNECTION_NAME=
RBRR_GCB_WORKER_POOL=

# Rubric repo
RBRR_RUBRIC_REPO_URL=

# Google Cloud Build settings
RBRR_GCB_MACHINE_TYPE=
RBRR_GCB_TIMEOUT=
RBRR_GCB_MIN_CONCURRENT_BUILDS=

# Secrets directory — contains all credential files (RBRA and RBRO format)
# Credential file paths are derived as kindle constants in rbdc_DerivedConstants.sh
RBRR_SECRETS_DIR=

# eof
RBRR_TEMPLATE

  bug_t "  Reset complete: ${z_rbrr}"
  bug_e
  bug_t "  Next: verify onboarding guide detects blank state:"
  buc_tabtarget "${RBZ_PAYOR_ONBOARDING}"
  buc_success "Regime reset to blank template"
}

######################################################################
# Furnish and Main

zrbrr_reset_furnish() {
  buc_doc_env "BURD_BUK_DIR          " "BUK module directory (dispatch-provided)"
  buc_doc_env "BURD_CONFIG_DIR       " "Configuration directory (dispatch-provided)"
  buc_doc_env "BURD_TOOLS_DIR        " "Project tools root directory (dispatch-provided)"
  buc_doc_env_done || return 0

  source "${BURD_CONFIG_DIR}/rbbc_constants.sh"  || buc_die "Failed to source rbbc_constants.sh"
  source "${BURD_BUK_DIR}/bug_guide.sh"           || buc_die "Failed to source bug_guide.sh"

  # Kindle zipper for tabtarget references (lightweight, no regime dependency)
  source "${BURD_BUK_DIR}/buz_zipper.sh"                             || buc_die "Failed to source buz_zipper.sh"
  source "${BURD_TOOLS_DIR}/${RBBC_kit_subdir}/rbz_zipper.sh"        || buc_die "Failed to source rbz_zipper.sh"
  zbuz_kindle
  zrbz_kindle
}

buc_execute rbrr_ "RBRR Reset" zrbrr_reset_furnish "$@"

# eof
