#!/bin/bash
#
# Copyright 2026 Scale Invariant, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Brad Hyslop <bhyslop@scaleinvariant.org>
#
# RBRR Reset CLI - Pre-kindle entry point for Marshal reset operations
#
# This CLI deliberately skips regime kindle/enforce so that reset
# can produce a blank regime (the middle-product state before
# onboarding populates valid values).

set -euo pipefail

source "${BURD_BUK_DIR}/buc_command.sh"

######################################################################
# Command Functions

rbrr_reset() {
  buc_doc_brief "Reset RBRR repo regime to blank template for release qualification"
  buc_doc_shown || return 0

  local -r z_rbrr="${RBBC_rbrr_file}"
  test -n "${z_rbrr}" || buc_die "RBBC_rbrr_file is empty"

  bug_section "Marshal Reset"
  bug_t "  Target: ${z_rbrr}"
  bug_t "  Infrastructure defaults and project conventions will be pre-filled."
  bug_t "  Site-specific fields will be blanked for onboarding."
  bug_t "  Credential files (RBRA/RBRO) are NOT touched."
  bug_e

  # Write RBRR template with sensible defaults pre-filled.
  # Infrastructure constants and project conventions are pre-selected;
  # site-specific fields are blank and populated during onboarding.
  # The onboarding guide (rbw-gPo) reviews all pre-selected values
  # as its first step — proceeding to Payor Establish is consent.
  cat > "${z_rbrr}" <<'RBRR_TEMPLATE'
#!/bin/bash
# Recipe Bottle Repository Configuration
# Generated by rbw-MR Marshal Reset.
# Run rbw-gPo (Payor Onboarding) to review defaults and populate site-specific fields.

# --- Pre-selected defaults (reviewed in onboarding step 1) ---

RBRR_DNS_SERVER=8.8.8.8
RBRR_GCB_MACHINE_TYPE=e2-standard-2
RBRR_GCB_TIMEOUT=1200s
RBRR_GCB_MIN_CONCURRENT_BUILDS=3

# Reference directory containing specs for all vessels: relative to project root
RBRR_VESSEL_DIR=rbev-vessels

RBRR_GCP_REGION=us-central1

# Secrets directory — contains all credential files (RBRA and RBRO format)
# Credential file paths are derived as kindle constants in rbdc_DerivedConstants.sh
RBRR_SECRETS_DIR=../station-files/secrets

# --- Site-specific (populated during onboarding) ---

RBRR_IGNITE_MACHINE_NAME=
RBRR_DEPLOY_MACHINE_NAME=

# Depot configuration items
RBRR_DEPOT_PROJECT_ID=
RBRR_GAR_REPOSITORY=
RBRR_CBV2_CONNECTION_NAME=
RBRR_GCB_WORKER_POOL=

# Rubric repo
RBRR_RUBRIC_REPO_URL=

# eof
RBRR_TEMPLATE

  bug_t "  Reset complete: ${z_rbrr}"
  bug_e
  bug_t "  Next: verify onboarding guide detects blank state:"
  buc_tabtarget "${RBZ_PAYOR_ONBOARDING}"
  buc_success "Regime reset to blank template"
}

######################################################################
# Furnish and Main

zrbrr_reset_furnish() {
  buc_doc_env "BURD_BUK_DIR          " "BUK module directory (dispatch-provided)"
  buc_doc_env "BURD_CONFIG_DIR       " "Configuration directory (dispatch-provided)"
  buc_doc_env "BURD_TOOLS_DIR        " "Project tools root directory (dispatch-provided)"
  buc_doc_env_done || return 0

  source "${BURD_CONFIG_DIR}/rbbc_constants.sh"  || buc_die "Failed to source rbbc_constants.sh"
  source "${BURD_BUK_DIR}/bug_guide.sh"           || buc_die "Failed to source bug_guide.sh"

  # Kindle zipper for tabtarget references (lightweight, no regime dependency)
  source "${BURD_BUK_DIR}/buz_zipper.sh"                             || buc_die "Failed to source buz_zipper.sh"
  source "${BURD_TOOLS_DIR}/${RBBC_kit_subdir}/rbz_zipper.sh"        || buc_die "Failed to source rbz_zipper.sh"
  zbuz_kindle
  zrbz_kindle
}

buc_execute rbrr_ "RBRR Reset" zrbrr_reset_furnish "$@"

# eof
