build_architectures: x86_64
history_dir:         RBM-history
recipes_dir:         RBM-recipes
recipe_pattern:      "*.dockerfile"
timeout-minutes:     60
concurrency:         2
max-parallel:        2
continue-on-error:   false
fail-fast:           false

