name: Container Build and Upload

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build_containers]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d__%H%M%S')"

      - name: Build and push containers
        run: |
          for dockerfile in RBM-recipes/*.dockerfile RBM-recipes/*.recipe; do
            if [ -f "$dockerfile" ]; then
              filename=$(basename "$dockerfile")
              build_label="${filename%.*}.${GITHUB_SHA::7}.${{ steps.timestamp.outputs.timestamp }}"
              
              echo "Building $build_label"
              
              # Create History Subdirectory
              mkdir -p "RBM-transcripts/$build_label"
              cp "$dockerfile" "RBM-transcripts/$build_label/"
              echo "${{ github.sha }}" > "RBM-transcripts/$build_label/commit.txt"
              
              # Attempt to build
              if docker build -t "ghcr.io/${{ github.repository }}:$build_label" -f "$dockerfile" . > "RBM-transcripts/$build_label/history.txt" 2>&1; then
                # If build successful, push to registry
                docker push "ghcr.io/${{ github.repository }}:$build_label"
                
                # Create digest.txt
                echo "Size: $(docker image inspect ghcr.io/${{ github.repository }}:$build_label --format='{{.Size}}')" > "RBM-transcripts/$build_label/digest.txt"
                echo "Build duration: $SECONDS seconds" >> "RBM-transcripts/$build_label/digest.txt"
              fi
            fi
          done

      - name: Commit History Subdirectory
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add RBM-transcripts
          git commit -m "Add build history for ${{ steps.timestamp.outputs.timestamp }}"
          git push
