= Project Title
Author Name <author@example.com>
:toc:
:toclevels: 3
:sectnums:
:sectnumlevels: 3

== Introduction

This is highly personal action planning support.

== MINIDRAMAS

=== Minidrama: CURRENT FOCUS: the Alpha Github Action

Here we go, lets see if I can get somewhere today!  This very day!

* **DONE** TODO: Pull all env vars down
* **WONT** TODO: MAYBE make dockerfiles crash if needed vars not set?
* **DONE** TODO: Confirm current local function on `*srjcl*`
* **DONE** TODO: Try use proper tabtarget arg crack
* **DONE** TODO: Recast nameplates to makestyle
* **DONE** TODO: Decide if NAMEPLATE_MONIKER ought to be an RBEV_ thing and apply
* TODO: construct makefile machinery to create the json for matrix config
* TODO: ??? Decide what to do around -> `rbm-P.SetupPodman.sh`

=== Minidrama: Using Claude to Write Claude Requirements

That worked evilly well!
At least at first glance...
I had several iterations of building out a requirements document.
That process went pretty well, I think.

I did ask claude to meet it, and on first glance it seems to have tried hard.
Oh I hate its makefile conventions, but maybe the problem is that mine are weird.
I'll definitely contemplate how I can get Claude to do my style makefiles.
Is that its own `claudex`?
Probably.

I'm out of time and energy for further dive into this, but that was productive.
There definitely is a vertigo here.

=== Minidrama: Local Image Studies

On startup this morning, I decided to play with my local images.
Whoa they're bigger than I expected!
It is seriously reducing what the minimum viable product should be.
No periodic autobuilds for darn sure.

=== Minidrama: Plan Ambiguity

I'm having a devil of a time making a plan to transfer the build of several dockerfiles into a Github Action where they get maintained in the Github Container Registry for use.
This isn't a thing I'm going to get meta good about, I don't think I'll do such things much in my life.
So, the path of baby steps...
Hmm.

Okay.

..

Wow, I instructed Claude to have a terse conversation and it went very well.
Wow!

What did I get out of it?

* Start with matrix from the get go
* Getting 'retro' package sets is a pain through the package manager.
* Bookkeeping eventually gets complex if shared layers, and I'll have a lot of those even naively
* Don't store transcripts in containers: better to have tracking files in repo
* 'Repository variables' is the way to go forward with config items, not facts in makefiles
* Keep with the 'one long list of apt update packages'
* No multi-stage container builds for a while
* I am liking the simple addition of a datestampped per build file to a repo place that is never edited by a human
* I don't fully grok run id and run number but those sound pretty good as anchor points.  Will still need dates though

=== Minidrama: Idea for "The Daily/ Weekly" autobuild

What if I make this system limit the number of times that dockerfiles are built per day/ week?
Configurable, of course.
And then, if the build fails, it sends me an email.
Aha thanks copilot!
Its sentance, not mine.

Anyway.

There would be ways to delete it, cause a restart, for sure.

I'm iffy on the cache management that Claude Github Actions pushed.
This might be a good alternative: no caches, and weekly might be the better unforced cadence. 

Daddy like...

Okay protoday I think...

=== Minidrama: Versioning Docker Images in the Cloud

I don't know precisely why this is such a no-see-um (funname?) topic.
Really very little traction, and I want the problem to go away.
But it won't...

Name and a User and a Tag and nothing else?
Tag as date?

Need good listing features, that's an easy one.
Why not camp on that?
For starters?

== DEFERRED OPEN ISSUES

This section contains reminders about future improvements, deferred for now.


[NOTE]
====
* BE VERY SURE THAT NASCENT ROGUE CANT PING EXCEPT ANTHROPIC
* Make the github outreach thing function
* Revise all filesystem names from MBSR to Recipe Muster 
* Rename Rogue to Bottle
* As per below suggest, use curlies for var substitutions
    https://claude.ai/chat/4b2aeb38-7dd8-4236-9d5a-389db50f919a
* Pull all build arguments out of dockerfiles, and instead introduce them into the makefile environment
* Prototype the usage of concept model keyphrases in this file via asciidoc includes
* Riddle a way to manage versioned docker images
* debug podman start/stop/start
* Explore creating a nonprivileged user to run the jupyter notebook (may help with shutdown)
* Decide whether to do a tabtarget generation flavor with a parameter that pulls parameter from name in script
* Solve the tabtarget dispatch script problem with clean environment and admin privileges for podman sufficent for sentry ip forwarding enabling
* I'm mixed as to whether rbc-console.mk ought to actually include the RBM core makefile...
* Scrub out all tabtargets for modern consistency
* Get real clear if I think a docker container advertising a port gets external network view
* Consider proper use of `unexport` concerning the tabtarget name parts for proper recursive invocation
* Make the startup script for rogue standalone external too
* Look into placing monitor file write late in the recipes for potentially better caching
* Cut down the diagnostic IP utilities found all over the place
* Create python github downloader with command spec that renders the safe ip rules
* OUCH consider if keep parse of -> `$ curl -v -s -I -X OPTIONS https://api.anthropic.com/v1/messages`
* Add a logging tabtarget dispatch variant
* Form an excellent opinion on what to do with logs of weekly builds
* Write up precepts section that asserts...
  * podman is trustable
  * github is trustable
  * manifesto of environment variables
  * manifesto of fume hoods
  * manifesto for recipe vs venv
* Write up an apologea for forcing environment variables to exist and using containers via the makefile, maybe stronger.  Red pill or blue pill?
* Recall Claude cool ideas for console colors
  https://claude.ai/chat/54a45100-0d5e-44a6-afce-4dc269e283a9
* Refresh whether rogue --privileged is required for function (and cut if not)
* Cut outreach from the matplotlib container
* Put pip after apk install
* Decide whether dockerfile is named in nameplate or implicit location from nameplate target
* Document the phony rule trick and everything else about the warped rules of makefile in this project
* Document the intriciacies of nameplate files well
* Clean up the nameplate themes strongly
* Cut startup script 5 second hack, probably with atomizing startup sequence
* Rename dockerfile to recipe or containerfile... Does this make the environment a 'cake'? I think it does...
* Try multiline docker arg/env for better maintenance
* Better name for 'instance of application' for crisp docs. 'Environment'?
* Make plantuml server variant that works with -> https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 or http://localhost:8080/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 blended
* Decide if sentry socat should be in a separate startup script rather than dockerfile (probably with atomization, yes)
* Make pretty non-internet jupyter maths variant
* Make integ check buried jupyter (i.e. flask executor only) with internet variant

* There may be parameters in the dockerfile that are simpler out here
* Consider rename all to BANDIT or PIRATE for ROGUE
* Cut the network diagnostic that is in the build context
* Strip back dnsmasq to _only_ serve the anthropic.com (or similar)
* Figure out how to inscribe parameters during build so they don't confuse (or risk) the environment later
* Sort out tests: automatic during build/setup, or explicit? Not all over the place
* Consistify WORKDIR
* Tee with error capture all the catted in scripts
* Make default dockerfile arg/env values really illegal
* Consider factoring out podman stop and then giving it a zero timeout; probably ought to manually stop and check logs for why it's slow
* Decide whether to mononame the docker env/arg to the makefile name, or drift it. Do it.
* Scrub out dockerfile environment variables unneeded in final env?
* Rethink the .sh-ization of the nameplate, specifically for including includes
* Really consider deprivilidgening ROGUE
* Consider a precedent rule that in parallel will stop containers before rmi and use in build and start
* Make choices concerning secondary port opens for the jupyter flask executor on top of jupyter
* Figure suppression of error -> time="2024-08-30T06:54:29-07:00" level=warning msg="Failed to obtain TTY size: The handle is invalid."
* Segregate nameplate checking to a subfile and explain there the unusability of a rule string for include directive
* Something not sitting right about machinations around the ALL target in above makefile, and double console include, and mbc path include
* Seriously consider making tabtarget names in this file more like zmbsr_xxx_rule and then hardcoding tabtarget to pass var, better for nesting
====

