#!/bin/bash
#
# Copyright 2026 Scale Invariant, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Brad Hyslop <bhyslop@scaleinvariant.org>
#
# BUE Exergue - stamp a build with the source position it was struck from
#
# An exergue is the ground below a coin's design carrying the mint mark and the
# date: the part of the striking that says WHERE AND WHEN, not what. A binary
# has the same need and no such ground, which is the whole of this module's job
# — it writes one, as a generated source file the build compiles in.
#
# The stamp is the newest FIRST-PARENT LANDING on the trunk counterpart that
# touched an elected source root. Three words in that sentence are load-bearing:
#
#   LANDING, never HEAD. A billet's own unlanded commits carry shas the
#   studbook journal cannot resolve, so a stamp read from HEAD names a position
#   no reader downstream can look up. The counterpart is read as this clone last
#   gleaned it and NO FETCH IS PERFORMED here — a build is not the place for
#   network. A stale counterpart understates the position, which errs toward
#   calling a fresh binary old; the opposite error would be the dangerous one.
#
#   FIRST-PARENT, so the position walks the trunk's own line rather than
#   descending into the merged branches whose commits never stood on it.
#
#   ELECTED, because "source" is a judgment: the roots file names it, and it is
#   the single authoritative statement of what counts. This module never guesses
#   the set and never carries a default for it.
#
# The elected roots ride into the generated file BESIDE the sha, as a second
# constant. That is not decoration: a consumer that means to ask "is this binary
# older than its source" must ask it over the same set the stamp was computed
# over, and compiling the set in beside the answer is what makes the two agree
# by construction rather than by two copies staying in step.
#
# WRITE-IF-CHANGED. The generated file is a cargo input, so an unconditional
# write dirties the fingerprint and forces a rebuild on every invocation. The
# content is composed first and compared before anything is touched.
#
# A build that cannot stamp DIES, here, by buc_die_now — there is no sentinel
# value, no "unknown", and no unstamped binary from a decorated build. Every
# fault path below is that rule.

set -euo pipefail

# Multiple inclusion guard
test -z "${ZBUE_SOURCED:-}" || buc_die_now "Module bue multiply sourced - check sourcing hierarchy"
ZBUE_SOURCED=1

# The generated file's own opening lines, carried as a constant so the warning a
# reader meets is stated once. It names the writer rather than the caller: a
# reader who finds this file dirty needs the door, and the door is here.
readonly BUE_exergue_banner="// GENERATED by Tools/buk/bue_exergue.sh - DO NOT EDIT, DO NOT COMMIT."

# Strike the exergue: compose the generated Rust module and write it only if its
# content differs from what already stands.
#
# The two constants are named from the OUT FILE'S OWN STEM, uppercased, so the
# module path and the constant it declares cannot drift apart and no caller has
# to state the pair a second time:
#
#   <STEM_UPPER>        the sha, a &str
#   <STEM_UPPER>_ROOTS  the elected roots, a &[&str]
#
# The trunk counterpart is RESOLVED HERE from the remote's recorded head rather
# than taken as a branch name, so no caller carries a copy of which branch this
# repository calls its trunk. Both consumers pass the remote and agree by having
# nothing to disagree about.
#
# Args: <repo_dir> <remote> <roots_file> <out_file>
#   repo_dir    the repository being built - the ONLY repository read
#   remote      the remote whose recorded head names the trunk, e.g. origin;
#               its counterpart ref is read as this clone last gleaned it and is
#               never fetched here
#   roots_file  the elected source roots, one repo-relative path per line;
#               blank lines and #-comments ignored
#   out_file    the generated Rust module to write (gitignored by its own repo)
bue_strike() {
  local -r z_repo="${1:-}"
  local -r z_remote="${2:-}"
  local -r z_roots="${3:-}"
  local -r z_out="${4:-}"

  test -n "${z_repo}"   || buc_die_now "bue_strike: repo_dir required"
  test -n "${z_remote}" || buc_die_now "bue_strike: remote required"
  test -n "${z_roots}"  || buc_die_now "bue_strike: roots_file required"
  test -n "${z_out}"    || buc_die_now "bue_strike: out_file required"

  test -d "${z_repo}" || buc_die_now "bue_strike: no such directory: ${z_repo}"

  # The git check is separate from the directory check above and states its own
  # grievance: a path that exists but carries no repository is the fault this
  # module is likeliest to meet in the field (a build run from a copied tree, an
  # extracted tarball), and "no such directory" would send its reader hunting a
  # typo that is not there.
  git -C "${z_repo}" rev-parse --git-dir > /dev/null 2>&1 \
    || buc_die_now "bue_strike: ${z_repo} is no git repository, so no source position can be read - a decorated build never ships an unstamped binary"

  test -f "${z_roots}" || buc_die_now "bue_strike: elected roots file not found: ${z_roots}"

  local -a z_root_list=()
  local z_line=""
  while IFS= read -r z_line || test -n "${z_line}"; do
    z_line="${z_line%%#*}"
    z_line="${z_line#"${z_line%%[![:space:]]*}"}"
    z_line="${z_line%"${z_line##*[![:space:]]}"}"
    test -n "${z_line}" || continue
    z_root_list+=("${z_line}")
  done < "${z_roots}"

  test "${#z_root_list[@]}" -gt 0 \
    || buc_die_now "bue_strike: the elected roots file ${z_roots} names no root - an empty election would stamp the whole repository's position over a set nothing was measured against"

  local z_head_ref=""
  z_head_ref=$(git -C "${z_repo}" symbolic-ref --quiet "refs/remotes/${z_remote}/HEAD") \
    || buc_die_now "bue_strike: ${z_repo} records no head for remote '${z_remote}', so the trunk counterpart cannot be named - run: git -C ${z_repo} remote set-head ${z_remote} -a"
  local -r z_trunk="${z_head_ref#refs/remotes/}"

  git -C "${z_repo}" rev-parse --verify --quiet "${z_trunk}^{commit}" > /dev/null \
    || buc_die_now "bue_strike: ${z_repo} knows no commit at ${z_trunk} - the trunk counterpart must be a ref this clone already holds; fetch it and rebuild"

  local z_sha=""
  z_sha=$(git -C "${z_repo}" log -1 --first-parent --format=%H "${z_trunk}" -- "${z_root_list[@]}") \
    || buc_die_now "bue_strike: could not read the newest landed source touch on ${z_trunk} in ${z_repo}"

  test -n "${z_sha}" \
    || buc_die_now "bue_strike: no landed commit on ${z_trunk} touches any elected root - the election in ${z_roots} names nothing this repository's trunk has ever changed"

  local z_stem="${z_out##*/}"
  z_stem="${z_stem%.rs}"
  local z_const=""
  z_const=$(printf '%s' "${z_stem}" | tr '[:lower:]' '[:upper:]')

  local z_body=""
  z_body="${BUE_exergue_banner}
//
// The source position this binary was struck from: the newest first-parent
// landing on ${z_trunk} that touched an elected root. The roots ride beside the
// sha deliberately - a reader asking whether this binary is older than its
// source must ask over the same set the sha was measured over.
//
// Election: ${z_roots##*/}

/// The newest landed source touch this build was struck from.
pub const ${z_const}: &str = \"${z_sha}\";

/// The elected source roots the sha above was measured over.
pub const ${z_const}_ROOTS: &[&str] = &[
"
  local z_root=""
  for z_root in "${z_root_list[@]}"; do
    z_body="${z_body}    \"${z_root}\",
"
  done
  z_body="${z_body}];

// eof
"

  # Write-if-changed. The comparison is on the composed content rather than on
  # the sha alone: an edit to the election moves the roots constant without
  # moving the sha, and a sha-only comparison would leave the file lying.
  if test -f "${z_out}" && printf '%s' "${z_body}" | cmp -s - "${z_out}"; then
    buc_log_args "Exergue: ${z_sha} (unchanged)"
    return 0
  fi

  local z_dir="${z_out%/*}"
  test -d "${z_dir}" || buc_die_now "bue_strike: no directory to write the exergue into: ${z_dir}"

  local z_tmp=""
  z_tmp="$(mktemp "${z_out}.XXXXXX")" || buc_die_now "bue_strike: could not create a temp file beside ${z_out}"
  printf '%s' "${z_body}" > "${z_tmp}" || buc_die_now "bue_strike: could not write ${z_tmp}"
  mv -f "${z_tmp}" "${z_out}" || buc_die_now "bue_strike: could not install ${z_out}"

  buc_log_args "Exergue: ${z_sha} (struck)"
}

# eof
