#!/bin/bash
#
# Copyright 2026 Scale Invariant, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Brad Hyslop <bhyslop@scaleinvariant.org>
#
# BUK Windows Commands
#
# Windows-specific automation commands that alter system configuration.
# These are commands (not handbooks) — they modify state on the target machine.
# Consumes buhw tinder constants for Windows paths and network constants.

set -euo pipefail

# Multiple inclusion detection
test -z "${ZBUWC_SOURCED:-}" || buc_die "Module buwc multiply sourced - check sourcing hierarchy"
ZBUWC_SOURCED=1

######################################################################
# Internal: Kindle and Sentinel

zbuwc_kindle() {
  test -z "${ZBUWC_KINDLED:-}" || buc_die "Module buwc already kindled"
  zbuhw_sentinel
  readonly ZBUWC_KINDLED=1
}

zbuwc_sentinel() {
  test "${ZBUWC_KINDLED:-}" = "1" || buc_die "Module buwc not kindled - call zbuwc_kindle first"
}

######################################################################
# External Functions (buwc_*)

buwc_install_key() {
  zbuwc_sentinel

  buc_doc_brief "Install BURN profile SSH key into Windows administrators authorized_keys (idempotent)"
  buc_doc_shown || return 0

  test -n "${BUZ_FOLIO:-}" || buc_die "Profile alias required (e.g., winhost-cyg)"

  command -v powershell.exe >/dev/null 2>&1 \
    || buc_die "powershell.exe not found — this command must run from WSL"

  zburn_build_key_line

  # Read existing file, remove old marker line, append new line — all via PowerShell
  local z_existing=""
  if z_existing=$(powershell.exe -Command "Get-Content -Path '${ZBUHW_ADMIN_AUTH_KEYS}' -ErrorAction SilentlyContinue" 2>/dev/null); then
    z_existing=$(printf '%s\n' "${z_existing}" | grep -v "${ZBURN_KEY_MARKER}" || true)
  fi

  {
    test -z "${z_existing}" || printf '%s\n' "${z_existing}"
    printf '%s\n' "${ZBURN_KEY_LINE}"
  } | powershell.exe -Command "\$input | Set-Content -Path '${ZBUHW_ADMIN_AUTH_KEYS}' -Force" \
    || buc_die "Failed to write authorized_keys (elevated terminal required)"

  # Windows admin authorized_keys requires specific ACL
  powershell.exe -Command "icacls '${ZBUHW_ADMIN_AUTH_KEYS}' /inheritance:r /grant 'Administrators:F' /grant 'SYSTEM:F'" \
    || buc_die "Failed to set authorized_keys permissions"

  buc_success "Key installed for ${BURN_ALIAS} in ${ZBUHW_ADMIN_AUTH_KEYS}"
}

buwc_bootstrap_sshd() {
  zbuwc_sentinel

  buc_doc_brief "Provision OpenSSH server on Windows via PowerShell from WSL"
  buc_doc_shown || return 0

  buc_require \
    "This will OVERWRITE sshd_config, restart sshd service, and create firewall rules on the Windows host." \
    "OVERWRITE"

  command -v powershell.exe >/dev/null 2>&1 \
    || buc_die "powershell.exe not found — this command must run from WSL"

  buc_step "Bootstrap: OpenSSH Server on Windows"

  # Step 1: Probe sshd
  buc_step "Probing OpenSSH Server..."
  local z_status=""
  if z_status=$(powershell.exe -Command 'Get-Service sshd -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Status' 2>&1); then
    z_status=$(printf '%s' "${z_status}" | tr -d '\r\n')
    buc_step "OpenSSH Server status: ${z_status}"
  else
    buc_step "OpenSSH Server not installed — installing..."
    powershell.exe -Command 'Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0' \
      || buc_die "Failed to install OpenSSH Server (elevated terminal required)"
    buc_step "OpenSSH Server installed"
  fi

  # Step 2: Write sshd_config from template
  buc_step "Writing sshd_config..."
  {
    echo "# Generated by buw-wcb — BURN bootstrap"
    echo "Port ${ZBUHW_SSH_PORT}"
    echo "PasswordAuthentication no"
    echo "PubkeyAuthentication yes"
    echo "PermitEmptyPasswords no"
    echo "AuthorizedKeysFile .ssh/authorized_keys"
    echo "Subsystem sftp sftp-server.exe"
    echo "Match Group administrators"
    echo "  AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys"
  } | powershell.exe -Command "\$input | Set-Content -Path '${ZBUHW_SSHD_CONFIG}' -Force" \
    || buc_die "Failed to write sshd_config (elevated terminal required)"
  buc_step "sshd_config written"

  # Validate sshd_config
  powershell.exe -Command "sshd -t -f '${ZBUHW_SSHD_CONFIG}'" \
    || buc_die "sshd_config validation failed — check config syntax"
  buc_step "sshd_config validated"

  # Step 3: Configure and start sshd service
  buc_step "Configuring sshd service..."
  powershell.exe -Command 'Set-Service -Name sshd -StartupType Automatic' \
    || buc_die "Failed to configure sshd service"
  powershell.exe -Command 'Restart-Service sshd' \
    || buc_die "Failed to restart sshd service"
  buc_step "sshd service configured and started"

  # Step 4: Firewall rule (idempotent)
  buc_step "Checking firewall rule..."
  if powershell.exe -Command "Get-NetFirewallRule -Name '${ZBUHW_FW_RULE_NAME}' -ErrorAction SilentlyContinue" >/dev/null 2>&1; then
    buc_step "Firewall rule already exists"
  else
    powershell.exe -Command "New-NetFirewallRule -Name '${ZBUHW_FW_RULE_NAME}' -DisplayName '${ZBUHW_FW_DISPLAY_NAME}' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort ${ZBUHW_SSH_PORT}" \
      || buc_die "Failed to create firewall rule"
    buc_step "Firewall rule created"
  fi

  # Step 5: Loopback verify
  buc_step "Verifying loopback SSH..."
  local z_whoami=""
  if z_whoami=$(ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no localhost whoami 2>&1); then
    z_whoami=$(printf '%s' "${z_whoami}" | tr -d '\r\n')
    buc_success "Bootstrap complete — loopback SSH: ${z_whoami}"
  else
    buc_warn "Loopback verify deferred (keys may need setup from client machine)"
    buc_step "Bootstrap structurally complete"
  fi
}

# eof
