// Copyright 2026 Scale Invariant, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The gangline's hurdles, driven over lures against a real cargo.
//!
//! EVERY ONE OF THESE DRIVES CARGO, for the muzzle's reason: a hurdle asserting
//! over a composed command line would prove only that this module spells a flag
//! the way this module believes it should. What can go wrong is the lock flag's
//! refusal arriving — or not arriving — where the door expects it, and only a
//! drive asks that.
//!
//! THE ORDER OF THE FIRST HURDLE IS ITS WHOLE POINT. It proves the wall before
//! it proves the door: the leash with the flag on must REFUSE first, or the
//! gangline that follows has re-derived a lock nothing was blocking, and the
//! hurdle would pass against a kennel whose lock discipline had quietly lapsed.

use super::bkcg_gangline::{bkcg_python, bkcg_Verdict, bkcg_gangline};
use super::bkth_heel::bkth_python_seated;
use super::bkcl_leash::bkcl_recall;
use super::bkcr_resolve::bkcr_resolve;
use super::bktu_lure::bktu_Lure;

/// The collar the hurdles resolve, over the lure's own crate.
const ZBKTG_COLLAR_NAME: &str = "suite-lure";

/// A collar over the lure's crate.
///
/// IT PERMITS AND ELECTS `hitch` FROM THE START, before the manifest names it.
/// The collar's fields are declarations about what this crate MAY link and what
/// its position is measured over, and both answers are the same before and after
/// the hitch — what changes at the hitch is the manifest, which is the whole
/// point of the hurdle. A collar edited in the same breath as the manifest would
/// make the hurdle prove two things at once and be able to say which one failed
/// for neither.
const ZBKTG_COLLAR: &str = "\
BKRR_COLLAR=\"suite-lure\"
BKRR_KIND=\"bknre_suite\"
BKRR_MANIFEST=\"Cargo.toml\"
BKRR_TARGET=\"bknre_manifest\"
BKRR_ROOTS=\"src \\
  hitch \\
  Cargo.toml\"
BKRR_FEATURES=\"\"
BKRR_PROFILE=\"test\"
BKRR_SPEND=\"bknre_reader\"
BKRR_TAMED_CRATES=\"hitch\"
BKRR_FERAL_CRATES=\"bknre_tamed\"
BKRR_MUZZLE=\".\"
BKRR_EXERGUE=\"bknre_unstruck\"
BKRR_RUNNER=\"bknre_cargo\"
BKRR_TONGUE=\"bknre_harness\"
";

/// The lock that answers a lure whose manifest names no dependency.
const ZBKTG_LOCK_BARE: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"lure\"
version = \"0.0.1\"
";

/// Stand up a lure holding one crate, its lock answering its manifest, and a
/// collar over it.
///
/// A PATH DEPENDENCY IS THE SHAPE EVERY HURDLE HERE USES, and it is chosen so
/// the drives reach no network: a path dependency has no registry closure, so
/// cargo re-derives the lock from the two manifests on disk and asks the world
/// nothing. That keeps these hurdles honest on a station behind the tackroom
/// fence, where a registry fetch would refuse rather than answer.
fn zbktg_lure(name: &str) -> bktu_Lure {
    let lure = bktu_Lure::bktu_compose(name);

    lure.bktu_write(
        "Cargo.toml",
        "[package]\nname = \"lure\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"lure\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write("Cargo.lock", ZBKTG_LOCK_BARE);
    lure.bktu_write("src/lib.rs", "pub fn seated() -> u8 {\n    1\n}\n");

    // The dependency's own crate stands from the start, so the manifest edit a
    // hurdle makes is one line rather than a tree.
    lure.bktu_write(
        "hitch/Cargo.toml",
        "[package]\nname = \"hitch\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"hitch\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write("hitch/src/lib.rs", "pub fn hitched() -> u8 {\n    2\n}\n");

    // THE MUZZLE DIRECTORY MUST HOLD A LIST, because the resolver reads a
    // muzzle naming a directory with no lint list as a finding — a muzzle
    // nothing wears. The list is empty of bars: this hurdle asks nothing about
    // linting, and an empty list stated in a file the collar names is the
    // opposite of a collar pointing at nothing.
    lure.bktu_write("clippy.toml", "disallowed-methods = []\n");

    lure.bktu_write("suite-lure/bkrr.env", ZBKTG_COLLAR);
    lure.bktu_commit("stand the gangline up");

    lure
}

/// Add the path dependency the lock does not answer, and commit it — so the
/// drives that follow meet a clean tree carrying a stale lock, which is the
/// exact standing this door is for.
fn zbktg_hitch(lure: &bktu_Lure) {
    lure.bktu_write(
        "Cargo.toml",
        "[package]\nname = \"lure\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"lure\"\npath = \"src/lib.rs\"\n\
         [dependencies]\nhitch = { path = \"hitch\" }\n",
    );
    lure.bktu_commit("hitch the dependency the lock does not answer");
}

/// Drive the leash WITH THE LOCK FLAG ON over the lure, and hand back whether
/// cargo accepted.
///
/// THE RECALLED FACE, because this hurdle reads an exit and nothing else. The
/// driven face would hand cargo this process's streams, and the verb asked here
/// answers with the whole metadata document — a page of JSON on the suite's
/// console, per drive, saying nothing the assertion reads. The two faces apply
/// one discipline, so the lock question is asked identically either way.
fn zbktg_leashed(lure: &bktu_Lure) -> bool {
    let manifest = lure.bktu_root().join("Cargo.toml");

    bkcl_recall(
        lure.bktu_root(),
        &manifest,
        "metadata",
        ["--format-version", "1"],
        &[],
    )
    .expect("cargo should be reachable")
    .run
    .bkcl_landed()
}

/// Re-derive the lure's lock through the door.
fn zbktg_gangline(lure: &bktu_Lure) -> bkcg_Verdict {
    let resolved = bkcr_resolve(lure.bktu_root(), ZBKTG_COLLAR_NAME)
        .expect("the lure's collar should resolve");

    assert!(
        resolved.findings.is_empty(),
        "the lure's own collar should conform: {:?}",
        resolved.findings
    );

    bkcg_gangline(lure.bktu_root(), &resolved.collar).expect("the door should reach cargo")
}

/// A manifest that gained a path dependency the lock does not answer: the leash
/// refuses, the gangline writes, the leash then accepts.
///
/// THE THREE STEPS ARE ONE HURDLE AND NOT THREE, because the middle one means
/// nothing without the two around it. A gangline that wrote a lock proves the
/// door did something; a leash that refuses before and accepts after proves it
/// did the RIGHT thing, which is the only claim worth a drive.
#[test]
fn bktg_the_door_writes_the_lock_the_leash_was_refusing() {
    let lure = zbktg_lure("hitched");
    zbktg_hitch(&lure);

    assert!(
        !zbktg_leashed(&lure),
        "the leash carries the lock flag, so a manifest whose lock does not answer it must REFUSE \
         — an acceptance here says the lock discipline has lapsed and the rest of this hurdle \
         would prove nothing"
    );

    assert_eq!(
        zbktg_gangline(&lure),
        bkcg_Verdict::Moved,
        "the door should report the lock as moved"
    );

    assert!(
        zbktg_leashed(&lure),
        "the lock the door wrote should be the one the leash accepts with the flag still on"
    );
}

/// A manifest whose lock already answers it: the door reports no change, and the
/// file's bytes stand identical.
///
/// THE BYTES ARE THE ASSERTION AND THE VERDICT IS THE CORROBORATION, in that
/// order of trust. A door that reported `Unmoved` while having rewritten the
/// file — same content, new mtime, or a re-serialization that differs in
/// whitespace — would leave a tree the door law then refuses, and the verdict
/// alone could not tell us.
#[test]
fn bktg_a_lock_that_already_answers_is_left_alone() {
    let lure = zbktg_lure("answered");
    let lock = lure.bktu_root().join("Cargo.lock");

    let before = std::fs::read(&lock).expect("the lure should carry a lock");

    assert_eq!(
        zbktg_gangline(&lure),
        bkcg_Verdict::Unmoved,
        "the door should report the lock as unmoved"
    );

    let after = std::fs::read(&lock).expect("the lock should still stand");

    assert_eq!(
        before, after,
        "a lock that already answers its manifest must come back byte-identical"
    );
}

/// The door is reached over a lure whose dependency is hitched but whose lock is
/// re-derived twice: the second drive finds nothing to do.
///
/// It stands beside the two above because the door's own output is the input to
/// its next drive, and a door that reported `Moved` forever would make the
/// notch-gangline-notch sequence unterminating.
#[test]
fn bktg_a_second_drive_over_its_own_output_finds_nothing() {
    let lure = zbktg_lure("twice");
    zbktg_hitch(&lure);

    assert_eq!(zbktg_gangline(&lure), bkcg_Verdict::Moved);
    assert_eq!(
        zbktg_gangline(&lure),
        bkcg_Verdict::Unmoved,
        "the door's own output must satisfy its next drive, or notch-gangline-notch never ends"
    );
}

/// The version an unplaced uv kibble declares — one the estate does not stand
/// on, so the residence it composes is one nothing ever wrote.
///
/// FABRICATED AND DELIBERATELY IMPOSSIBLE, so a bump of the estate's own pin can
/// never make this seat accidentally placed.
const ZBKTG_UV_UNPLACED: &str = "0.0.0-unplaced";

/// The python lock re-derived over a manifest that has not moved.
///
/// THE BYTES ARE THE ASSERTION AND NOT THE EXIT. uv exits 0 either way — a lock
/// that already answers its manifest is a no-op it reports as success — so a
/// hurdle reading the exit would pass against a door that re-resolved the world
/// on every drive.
#[test]
fn bktg_a_python_lock_over_an_unmoved_manifest_is_re_derived_byte_identical() {
    let seated = bkth_python_seated("gangline-python-unmoved", ">=3.12", "");

    let lock = seated.project.join("uv.lock");

    let before = std::fs::read(&lock).expect("the seated lock stands before the door is driven");

    let verdict = bkcg_python(seated.lure.bktu_root(), &seated.collar, &seated.seat)
        .unwrap_or_else(|err| panic!("the door refused an authored project: {}", err));

    assert_eq!(
        verdict,
        bkcg_Verdict::Unmoved,
        "an unmoved manifest re-derived to a lock the door called moved"
    );

    let after = std::fs::read(&lock).expect("the lock still reads");

    assert_eq!(
        before, after,
        "the lock at {} moved under a manifest that did not",
        lock.display()
    );
}

/// The python lock rewritten once its manifest moves past it.
///
/// THE PROJECT STAYS DEPENDENCY-FREE AND THE MANIFEST MOVES ANYWAY, by declaring
/// a version floor the authored resolution never accounted for. A dependency
/// would reach an index, which is what parts a lock hurdle from a resolution
/// one; a floor moves the lock's own recorded requirement and reaches nothing.
#[test]
fn bktg_a_python_lock_is_re_derived_once_its_manifest_moves() {
    let seated = bkth_python_seated("gangline-python-moved", ">=3.12", "");

    let lock = seated.project.join("uv.lock");

    let before = std::fs::read(&lock).expect("the seated lock stands as this hurdle's control");

    seated.lure.bktu_write(
        "project/pyproject.toml",
        "[project]\nname = \"lure\"\nversion = \"0.0.1\"\nrequires-python = \">=3.12.7\"\n",
    );

    let verdict = bkcg_python(seated.lure.bktu_root(), &seated.collar, &seated.seat)
        .unwrap_or_else(|err| panic!("the door refused a moved manifest: {}", err));

    assert_eq!(
        verdict,
        bkcg_Verdict::Moved,
        "a moved manifest re-derived to a lock the door called unmoved"
    );

    let after = std::fs::read(&lock).expect("the re-derived lock reads");

    assert_ne!(
        before, after,
        "the lock at {} did not move under a manifest that did",
        lock.display()
    );

    // AND IT IS LEFT DIRTY RATHER THAN COMMITTED, which is the door's whole
    // posture: the operator reads the diff before it is banked.
    assert!(
        lock.is_file(),
        "no lock stands at {} after a re-derivation the door called moved",
        lock.display()
    );
}

/// uv absent from its kibble residence refuses, and the refusal names the door
/// that places one.
///
/// THE CONTROL IS DRIVEN FIRST AND IS THE HURDLE'S OTHER HALF. A refusal proven
/// against a lure nothing ever worked in proves an absence rather than a gate,
/// so this drives the SAME lure with the kibble placed, takes its verdict, and
/// only then moves the declaration out from under the residence.
#[test]
fn bktg_a_python_gangline_with_uv_unplaced_refuses_naming_the_converge() {
    let seated = bkth_python_seated("gangline-python-unplaced", ">=3.12", "");

    bkcg_python(seated.lure.bktu_root(), &seated.collar, &seated.seat).unwrap_or_else(|err| {
        panic!(
            "the control: the door answers this lure while uv stands at its residence, and it \
             refused instead: {}",
            err
        )
    });

    seated.lure.bktu_uv_seat_unplaced(ZBKTG_UV_UNPLACED);

    let said = bkcg_python(seated.lure.bktu_root(), &seated.collar, &seated.seat)
        .expect_err("a uv the tackroom never placed refuses the drive");

    assert!(
        said.contains("heel"),
        "the refusal does not name the door that places a kibble: {}",
        said
    );
}

// eof
