// Copyright 2026 Scale Invariant, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The resolver's hurdles, driven over a lure carrying a real two-crate closure.
//!
//! EVERY PROOF IS DRIVEN AGAINST REAL CARGO. The closure reading and the
//! direct-dependency reading are the two this crate could most easily fake, and
//! faking them would prove only that a fixture agrees with itself: the lure
//! stands up an actual crate with an actual path dependency, and cargo is asked
//! about it through the leash exactly as a door would ask.
//!
//! THE INVERSIONS ARE PLANTED IN THE LURE, never in a committed collar. A
//! fixture collar standing in this repository would be a real collar to every
//! door that walks the tree, which is the reason lures exist at all
//! (BKSLR-Lure.adoc).

use super::bkcr_resolve::{bkcr_resolve, bkcr_walk};
use super::bktu_lure::bktu_Lure;

/// The collar the lure carries when nothing is inverted.
const ZBKTR_SOUND: &str = "\
BKRR_COLLAR=\"suite-lure\"
BKRR_KIND=\"bknre_suite\"
BKRR_MANIFEST=\"Cargo.toml\"
BKRR_TARGET=\"bknre_manifest\"
BKRR_ROOTS=\"src \\
  inner \\
  probe \\
  Cargo.toml\"
BKRR_FEATURES=\"\"
BKRR_PROFILE=\"test\"
BKRR_SPEND=\"bknre_reader\"
BKRR_TAMED_CRATES=\"inner probe\"
BKRR_FERAL_CRATES=\"bknre_tamed\"
BKRR_MUZZLE=\".\"
BKRR_EXERGUE=\"bknre_unstruck\"
BKRR_RUNNER=\"bknre_cargo\"
BKRR_TONGUE=\"bknre_harness\"
";

/// The same collar declaring an APP rather than a suite, and dropping the
/// dev-dependency from both proofs — which is what makes it sound: cargo
/// compiles a dev-dependency into a test target and never into a binary.
const ZBKTR_APP: &str = "\
BKRR_COLLAR=\"app-lure\"
BKRR_KIND=\"bknre_app\"
BKRR_MANIFEST=\"Cargo.toml\"
BKRR_TARGET=\"lure\"
BKRR_ROOTS=\"src \\
  inner \\
  Cargo.toml\"
BKRR_FEATURES=\"\"
BKRR_PROFILE=\"release\"
BKRR_SPEND=\"bknre_reader\"
BKRR_TAMED_CRATES=\"inner\"
BKRR_FERAL_CRATES=\"bknre_tamed\"
BKRR_MUZZLE=\".\"
BKRR_EXERGUE=\"bknre_unstruck\"
BKRR_RESIDENCE=\"target/release\"
BKRR_BYNAME=\"lure\"
";

/// Stand up a lure holding a crate, a local dependency of that crate, a local
/// DEV dependency beside it, a muzzle, and one sound collar over all of it.
fn zbktr_kennel(name: &str) -> bktu_Lure {
    let lure = bktu_Lure::bktu_compose(name);

    lure.bktu_write(
        "Cargo.toml",
        "[package]\nname = \"lure\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"lure\"\npath = \"src/lib.rs\"\n\
         [dependencies]\ninner = { path = \"inner\" }\n\
         [dev-dependencies]\nprobe = { path = \"probe\" }\n",
    );
    lure.bktu_write(
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\nname = \"inner\"\nversion = \"0.0.1\"\n\n\
         [[package]]\nname = \"lure\"\nversion = \"0.0.1\"\n\
         dependencies = [\n \"inner\",\n \"probe\",\n]\n\n\
         [[package]]\nname = \"probe\"\nversion = \"0.0.1\"\n",
    );
    lure.bktu_write("src/lib.rs", "// eof\n");
    lure.bktu_write(
        "inner/Cargo.toml",
        "[package]\nname = \"inner\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"inner\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write("inner/src/lib.rs", "// eof\n");
    lure.bktu_write(
        "probe/Cargo.toml",
        "[package]\nname = \"probe\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"probe\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write("probe/src/lib.rs", "// eof\n");
    lure.bktu_write("clippy.toml", "# the lure's muzzle\n");
    lure.bktu_write("suite-lure/bkrr.env", ZBKTR_SOUND);
    lure.bktu_commit("stand the collar up");

    lure
}

/// Every finding against the lure's collar, as one string a hurdle can read.
fn zbktr_findings(lure: &bktu_Lure, name: &str) -> Vec<String> {
    bkcr_resolve(lure.bktu_root(), name)
        .unwrap_or_else(|err| panic!("'{}' should resolve in the lure: {}", name, err))
        .findings
}

/// The walk finds a collar wherever it stands, and steps over a build directory
/// rather than reading whatever a compiler happened to leave there.
#[test]
fn bktr_the_walk_finds_collars_and_steps_over_a_build_directory() {
    let lure = zbktr_kennel("walk");
    lure.bktu_write("target/suite-lure/bkrr.env", ZBKTR_SOUND);
    lure.bktu_write("inner/app-inner/bkrr.env", ZBKTR_SOUND);

    let found = bkcr_walk(lure.bktu_root()).expect("the lure is walkable");

    let named: Vec<String> = found
        .iter()
        .map(|held| held.display().to_string())
        .collect();

    assert!(named.contains(&"suite-lure".to_string()), "found: {:?}", named);
    assert!(named.contains(&"inner/app-inner".to_string()), "found: {:?}", named);
    assert!(
        !named.iter().any(|held| held.starts_with("target")),
        "a build directory holds no collar and is stepped over by name: {:?}",
        named
    );
}

/// THE CONTROL FOR EVERY INVERSION BELOW. A sound collar carries no finding at
/// all — which is what makes each inversion's finding a statement about the
/// inversion rather than about the fixture.
#[test]
fn bktr_a_sound_collar_carries_no_finding() {
    let lure = zbktr_kennel("sound");
    let findings = zbktr_findings(&lure, "suite-lure");

    assert!(
        findings.is_empty(),
        "the sound collar must carry no finding, and it carries: {:?}",
        findings
    );
}

/// The identity law: the declared name and the instance directory's name are
/// one.
#[test]
fn bktr_an_identity_mismatch_is_a_finding() {
    let lure = zbktr_kennel("identity");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("\"suite-lure\"", "\"suite-elsewhere\""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("suite-elsewhere"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("BKRR_COLLAR"), "it reads: {}", findings[0]);
}

/// A local dependency the elected roots do not reach is a finding, because a
/// position measured over those roots would not move when that crate's sources
/// do.
#[test]
fn bktr_an_unelected_local_dependency_is_a_finding() {
    let lure = zbktr_kennel("unelected");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("  inner \\\n", ""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("BKRR_ROOTS"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("inner"), "it reads: {}", findings[0]);
}

/// A direct dependency NEITHER LIST NAMES is a finding, local or not: the
/// field's job is that nothing links in unnoticed, and the guard reads the union
/// of the two (BKSCL-Collar.adoc "The tamed and the feral").
#[test]
fn bktr_an_unpermitted_direct_dependency_is_a_finding() {
    let lure = zbktr_kennel("unpermitted");

    assert!(
        zbktr_findings(&lure, "suite-lure").is_empty(),
        "the sound collar names every direct dependency and owes no finding"
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_TAMED_CRATES=\"inner probe\"", "BKRR_TAMED_CRATES=\"probe\""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("BKRR_TAMED_CRATES"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("BKRR_FERAL_CRATES"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("inner"), "it reads: {}", findings[0]);
}

/// A FERAL CRATE IS REFUSED, NEVER PROVISIONED (BKSCL-Collar.adoc BKr_4n2).
/// The field admits the none-sprue alone at MVP, so a crate named beside it
/// refuses at validation — and the finding CITES THE RIVET, which is what
/// carries a reader from the refusal to the class and to its repair.
#[test]
fn bktr_a_feral_crate_is_refused_citing_the_rivet() {
    let lure = zbktr_kennel("feral-named");

    assert!(
        zbktr_findings(&lure, "suite-lure").is_empty(),
        "the sound collar declares nothing feral and owes no finding"
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace(
            "BKRR_FERAL_CRATES=\"bknre_tamed\"",
            "BKRR_FERAL_CRATES=\"fetcher\"",
        ),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("BKr_4n2"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("fetcher"), "it reads: {}", findings[0]);
}

/// THE FIELD IS ASKED AT EVERY COLLAR, which is the whole reason a list admitting
/// one value is owed rather than tidy: an absence cannot be told from a
/// declaration, and the question would then go unasked wherever it was skipped.
#[test]
fn bktr_a_collar_lacking_the_feral_field_is_a_finding() {
    let lure = zbktr_kennel("feral-absent");

    assert!(
        zbktr_findings(&lure, "suite-lure").is_empty(),
        "the sound collar declares the field and owes no finding"
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_FERAL_CRATES=\"bknre_tamed\"\n", ""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("BKRR_FERAL_CRATES"), "it reads: {}", findings[0]);
    assert!(findings[0].contains("is not declared"), "it reads: {}", findings[0]);
}

/// THE UNION IS WHAT THE GUARD READS, and this is the arm that proves it: a
/// direct dependency named in the FERAL list alone is declared, so the omission
/// reading stays silent about it and the rivet is what refuses it. Without this
/// hurdle the guard could read the tamed list alone and every other hurdle would
/// still pass, the two lists being disjoint everywhere else they are driven.
#[test]
fn bktr_the_feral_half_of_the_union_is_a_declaration() {
    let lure = zbktr_kennel("union-feral");

    assert!(
        zbktr_findings(&lure, "suite-lure").is_empty(),
        "the sound collar names every direct dependency and owes no finding"
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND
            .replace("BKRR_TAMED_CRATES=\"inner probe\"", "BKRR_TAMED_CRATES=\"probe\"")
            .replace(
                "BKRR_FERAL_CRATES=\"bknre_tamed\"",
                "BKRR_FERAL_CRATES=\"inner\"",
            ),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("BKr_4n2"), "it reads: {}", findings[0]);
    assert!(
        !findings.iter().any(|held| held.contains("neither")),
        "a crate the feral list names is declared, whatever else is owed about it: {:?}",
        findings
    );
}

/// THE TWO LISTS ARE DISJOINT, and a crate standing in both says two
/// contradictory things about one dependency. The finding names both fields, so
/// the reading that repairs it is the one the refusal describes.
#[test]
fn bktr_a_crate_in_both_lists_is_a_finding() {
    let lure = zbktr_kennel("both-lists");

    assert!(
        zbktr_findings(&lure, "suite-lure").is_empty(),
        "the sound collar's two lists are disjoint and owe no finding"
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace(
            "BKRR_FERAL_CRATES=\"bknre_tamed\"",
            "BKRR_FERAL_CRATES=\"inner\"",
        ),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    // The rivet refuses the name as well, which is no duplicate: one reading is
    // about the class the name was put in, the other about its standing in two
    // lists at once.
    assert_eq!(findings.len(), 2, "findings: {:?}", findings);
    assert!(
        findings.iter().any(|held| {
            held.contains("BKRR_TAMED_CRATES")
                && held.contains("BKRR_FERAL_CRATES")
                && held.contains("inner")
        }),
        "findings: {:?}",
        findings
    );
}

/// The muzzle directory must stand, and must hold the lint list. Both arms,
/// because a directory that exists and holds nothing is the likelier mistake.
#[test]
fn bktr_a_muzzle_that_is_not_there_is_a_finding() {
    let lure = zbktr_kennel("muzzle-absent");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_MUZZLE=\".\"", "BKRR_MUZZLE=\"nowhere\""),
    );

    let absent = zbktr_findings(&lure, "suite-lure");
    assert_eq!(absent.len(), 1, "findings: {:?}", absent);
    assert!(absent[0].contains("no directory stands"), "it reads: {}", absent[0]);

    lure.bktu_write("bare/keep.txt", "\n");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_MUZZLE=\".\"", "BKRR_MUZZLE=\"bare\""),
    );

    let empty = zbktr_findings(&lure, "suite-lure");
    assert_eq!(empty.len(), 1, "findings: {:?}", empty);
    assert!(empty[0].contains("clippy.toml"), "it reads: {}", empty[0]);
}

/// A missing field is a finding, and so is one belonging to the other kind — the
/// kind decides the roster, which is why it is declared rather than inferred.
#[test]
fn bktr_the_declared_roster_is_held_to_the_kind() {
    let lure = zbktr_kennel("roster");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND
            .replace("BKRR_TONGUE=\"bknre_harness\"\n", "")
            .replace("BKRR_PROFILE=\"test\"", "BKRR_PROFILE=\"test\"\nBKRR_RESIDENCE=\"target\""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert!(
        findings.iter().any(|held| held.contains("BKRR_TONGUE")),
        "a missing field of this kind is a finding: {:?}",
        findings
    );
    assert!(
        findings.iter().any(|held| held.contains("BKRR_RESIDENCE")),
        "a field of the other kind is a finding: {:?}",
        findings
    );
}

/// A value outside an enum's roster is a finding naming what the roster admits.
#[test]
fn bktr_a_bare_enum_value_is_a_finding() {
    let lure = zbktr_kennel("enum");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_RUNNER=\"bknre_cargo\"", "BKRR_RUNNER=\"cargo\""),
    );

    let findings = zbktr_findings(&lure, "suite-lure");

    assert_eq!(findings.len(), 1, "findings: {:?}", findings);
    assert!(findings[0].contains("bknre_cargo"), "it reads: {}", findings[0]);
}

/// A name standing at two instances names no collar, and the refusal carries
/// BOTH paths — the repair is to rename one of them, and a reader told only that
/// the name is doubled has been handed a search.
#[test]
fn bktr_a_name_found_twice_refuses_naming_both() {
    let lure = zbktr_kennel("doubled");
    lure.bktu_write("inner/suite-lure/bkrr.env", ZBKTR_SOUND);

    let refusal = bkcr_resolve(lure.bktu_root(), "suite-lure")
        .expect_err("a doubled name resolves to no collar");

    assert!(refusal.contains("suite-lure/bkrr.env"), "it reads: {}", refusal);
    assert!(refusal.contains("inner/suite-lure/bkrr.env"), "it reads: {}", refusal);
}

/// A name that stands nowhere refuses and says what DOES stand, so the reader is
/// not left to run the walk again by hand.
#[test]
fn bktr_an_unknown_name_refuses_saying_what_stands() {
    let lure = zbktr_kennel("unknown");

    let refusal = bkcr_resolve(lure.bktu_root(), "suite-elsewhere")
        .expect_err("a name that stands nowhere must refuse");

    assert!(refusal.contains("suite-elsewhere"), "it reads: {}", refusal);
    assert!(refusal.contains("suite-lure"), "it reads: {}", refusal);
}

/// A collar file outside the catena law refuses at the reader, before any proof
/// is attempted — the reader is the one place that law is honored, and the
/// resolver does not second-guess it.
#[test]
fn bktr_a_collar_outside_the_catena_law_refuses_at_the_reader() {
    let lure = zbktr_kennel("unreadable");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace("BKRR_PROFILE=\"test\"", "BKRR_PROFILE='test'"),
    );

    let refusal = bkcr_resolve(lure.bktu_root(), "suite-lure")
        .expect_err("a file outside the subset must refuse");

    assert!(refusal.contains("single-quoted"), "it reads: {}", refusal);
}

/// THE KIND DECIDES WHICH DEPENDENCIES COUNT, and this is the pair that shows
/// it: one lure, one manifest, one dev-dependency, and two collars over it that
/// differ in their kind and in nothing else that matters here.
///
/// The app is SOUND while naming neither `probe` in its allow list nor its
/// directory in its roots, because cargo compiles a dev-dependency into a test
/// target and never into a binary. The suite carrying the same omission is not.
/// Driven as a pair rather than as two hurdles: either half alone would pass
/// under a validator that simply ignored dev-dependencies, and only the contrast
/// says the kind did the work.
#[test]
fn bktr_the_kind_decides_whether_a_dev_dependency_counts() {
    let lure = zbktr_kennel("dev-kind");

    lure.bktu_write("app-lure/bkrr.env", ZBKTR_APP);
    let app = zbktr_findings(&lure, "app-lure");
    assert!(
        app.is_empty(),
        "an app is not compiled with its crate's dev-dependencies, so it owes no declaration \
         about one: {:?}",
        app
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND
            .replace("  probe \\\n", "")
            .replace("BKRR_TAMED_CRATES=\"inner probe\"", "BKRR_TAMED_CRATES=\"inner\""),
    );
    let suite = zbktr_findings(&lure, "suite-lure");

    assert_eq!(suite.len(), 2, "findings: {:?}", suite);
    assert!(
        suite.iter().any(|held| held.contains("BKRR_TAMED_CRATES") && held.contains("probe")),
        "findings: {:?}",
        suite
    );
    assert!(
        suite.iter().any(|held| held.contains("BKRR_ROOTS") && held.contains("probe")),
        "findings: {:?}",
        suite
    );
}

// eof

/// THE EXERGUE AND ITS DOORS MOVE TOGETHER, both directions. The half that
/// matters is a file declared with no door, because a refusal composed from it
/// would name nothing where the whole point of the field is to name the door to
/// run; the other half is the ordinary authoring slip and is checked so it
/// cannot rot into the first.
#[test]
fn bktr_an_exergue_without_its_door_is_a_finding() {
    let lure = zbktr_kennel("exergue-unpaired");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace(
            "BKRR_EXERGUE=\"bknre_unstruck\"",
            "BKRR_EXERGUE=\"src/gen_exergue.rs\"",
        ),
    );

    let orphan = zbktr_findings(&lure, "suite-lure");
    assert_eq!(orphan.len(), 1, "findings: {:?}", orphan);
    assert!(
        orphan[0].contains("BKRR_STRIKE"),
        "it names the vacant field: {}",
        orphan[0]
    );

    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace(
            "BKRR_EXERGUE=\"bknre_unstruck\"",
            "BKRR_EXERGUE=\"bknre_unstruck\"\nBKRR_STRIKE=\"tt/nowhere.sh\"",
        ),
    );

    let idle = zbktr_findings(&lure, "suite-lure");
    assert_eq!(idle.len(), 1, "findings: {:?}", idle);
    assert!(
        idle[0].contains("strike nothing"),
        "it names the door that writes nothing: {}",
        idle[0]
    );
}

/// THE PRESENCE READING EVERY COMPILE ROAD TAKES, proven here at the one place
/// it is implemented so the three roads can be proven to CALL it rather than
/// each re-proving what it says.
///
/// BOTH ARMS, and the standing arm is what keeps the absent arm honest: a
/// reading that refused unconditionally would pass the first assertion having
/// proven nothing about whether it can tell a file that stands from one that
/// does not.
#[test]
fn bktr_an_absent_exergue_refuses_and_names_the_doors() {
    let lure = zbktr_kennel("exergue-absent");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        &ZBKTR_SOUND.replace(
            "BKRR_EXERGUE=\"bknre_unstruck\"",
            "BKRR_EXERGUE=\"src/gen_exergue.rs\"\nBKRR_STRIKE=\"tt/lure-b.Build.sh\"",
        ),
    );

    let resolved =
        bkcr_resolve(lure.bktu_root(), "suite-lure").expect("the collar should resolve");

    let refusal = super::bkcr_resolve::bkcr_exergue_stands(lure.bktu_root(), &resolved.collar)
        .expect_err("an exergue that does not stand refuses");
    assert!(
        refusal.contains("src/gen_exergue.rs"),
        "it names the file that is missing: {}",
        refusal
    );
    assert!(
        refusal.contains("tt/lure-b.Build.sh"),
        "it names the door that writes it, which is the whole reason this reading exists: {}",
        refusal
    );

    // THE SAME COLLAR, THE FILE NOW STANDING. Nothing else moves, so a reading
    // that still refused would be refusing on the declaration rather than on the
    // tree.
    lure.bktu_write("src/gen_exergue.rs", "// struck by the hurdle\n");
    super::bkcr_resolve::bkcr_exergue_stands(lure.bktu_root(), &resolved.collar)
        .expect("an exergue that stands is no refusal");

    // AND A COLLAR DECLARING NONE IS UNAFFECTED, which is what every other
    // collar in the estate declares: the reading must be silent there, or it
    // would refuse over a tree that owes it nothing. Proven against the sound
    // collar, whose declaration is the unstruck token and whose named file was
    // never written.
    lure.bktu_write("suite-lure/bkrr.env", ZBKTR_SOUND);
    let unstruck =
        bkcr_resolve(lure.bktu_root(), "suite-lure").expect("the collar should resolve");
    assert!(
        unstruck.collar.bkcr_exergue().is_empty(),
        "the unstruck token declares no exergue to stand"
    );
    super::bkcr_resolve::bkcr_exergue_stands(lure.bktu_root(), &unstruck.collar)
        .expect("a collar declaring no exergue is never refused for one");
}
