// Copyright 2026 Scale Invariant, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The muzzle's hurdles, driven over lures against a real linter.
//!
//! EVERY ONE OF THESE DRIVES CARGO. A hurdle that asserted over a composed
//! command line would prove that this module spells a flag the way this module
//! believes it should, which is the one thing that cannot go wrong here — what
//! can go wrong is the linter answering differently than the door reads it, and
//! only a drive asks that.

use super::bkcz_muzzle::{bkcz_Verdict, bkcz_lint};
use super::bkcr_resolve::bkcr_resolve;
use super::bktu_lure::bktu_Lure;

/// The sentence the lure's lint list teaches, and the surface it names.
const ZBKTZ_SENTENCE: &str = "reach for the shared seat instead";

/// The lure's lint list: one entry, carrying its sentence, exactly as the
/// sheaf's every-bar-states-its-sentence clause requires of a real one.
const ZBKTZ_LIST: &str = concat!(
    "disallowed-methods = [\n",
    "  { path = \"std::env::temp_dir\", reason = \"reach for the shared seat instead\" },\n",
    "]\n"
);

/// A collar over the lure's crate, with the muzzle directory left to the hurdle.
fn zbktz_collar(muzzle: &str) -> String {
    format!(
        "\
BKRR_COLLAR=\"suite-lure\"
BKRR_KIND=\"bknre_suite\"
BKRR_MANIFEST=\"Cargo.toml\"
BKRR_TARGET=\"bknre_manifest\"
BKRR_ROOTS=\"src \\
  Cargo.toml\"
BKRR_FEATURES=\"\"
BKRR_PROFILE=\"test\"
BKRR_SPEND=\"bknre_reader\"
BKRR_TAMED_CRATES=\"\"
BKRR_FERAL_CRATES=\"bknre_tamed\"
BKRR_MUZZLE=\"{}\"
BKRR_EXERGUE=\"bknre_unstruck\"
BKRR_RUNNER=\"bknre_cargo\"
BKRR_TONGUE=\"bknre_harness\"
",
        muzzle
    )
}

/// Stand up a lure holding one crate with no dependencies, its lint list at the
/// named directory, and a collar pointing at that directory.
///
/// `body` is the crate's whole source, so a hurdle plants exactly the call it
/// means to ask about.
fn zbktz_kennel(name: &str, muzzle_at: &str, body: &str) -> bktu_Lure {
    let lure = bktu_Lure::bktu_compose(name);

    lure.bktu_write(
        "Cargo.toml",
        "[package]\nname = \"lure\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"lure\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write(
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\nname = \"lure\"\nversion = \"0.0.1\"\n",
    );
    lure.bktu_write("src/lib.rs", body);

    let seat = if muzzle_at == "." {
        "clippy.toml".to_string()
    } else {
        format!("{}/clippy.toml", muzzle_at)
    };
    lure.bktu_write(&seat, ZBKTZ_LIST);

    lure.bktu_write("suite-lure/bkrr.env", &zbktz_collar(muzzle_at));
    lure.bktu_commit("stand the muzzle up");

    lure
}

/// Lint the lure's one collar.
fn zbktz_lint(lure: &bktu_Lure) -> bkcz_Verdict {
    let resolved = bkcr_resolve(lure.bktu_root(), "suite-lure")
        .expect("the lure's collar should resolve");

    assert!(
        resolved.findings.is_empty(),
        "the lure's own collar should conform: {:?}",
        resolved.findings
    );

    bkcz_lint(lure.bktu_root(), &resolved.collar).expect("the linter should be reachable")
}

/// A crate calling nothing the list bars lints clean.
#[test]
fn bktz_a_crate_calling_nothing_barred_is_clean() {
    let lure = zbktz_kennel(
        "clean",
        ".",
        "pub fn seated() -> std::path::PathBuf {\n    std::path::PathBuf::from(\"/seat\")\n}\n",
    );

    assert!(
        matches!(zbktz_lint(&lure), bkcz_Verdict::Clean(_)),
        "a crate calling nothing the list bars should lint clean"
    );
}

/// A barred call refuses, and the report carries the ENTRY'S OWN SENTENCE.
///
/// The sentence is what is asserted rather than the refusal, because the
/// sentence is the entry's whole teaching surface: a report that named the rule
/// and not the surface to adopt would tell an author only that a call is
/// forbidden.
#[test]
fn bktz_a_barred_call_refuses_with_its_sentence() {
    let lure = zbktz_kennel(
        "barred",
        ".",
        "pub fn seated() -> std::path::PathBuf {\n    std::env::temp_dir()\n}\n",
    );

    match zbktz_lint(&lure) {
        bkcz_Verdict::Refused(report) => assert!(
            report.contains(ZBKTZ_SENTENCE),
            "the refusal should carry the entry's sentence: {}",
            report
        ),
        other => panic!("a barred call should refuse: {:?}", other),
    }
}

/// THE LIST IS STATED AND NEVER SEARCHED FOR, proven where the two answers
/// differ: the list stands in a directory the crate root does not contain, so
/// the linter's own upward search would find nothing and report the crate clean.
/// The bar firing is the proof that the collar's field decided which list
/// governs.
#[test]
fn bktz_the_list_governs_from_where_the_collar_names_it() {
    let lure = zbktz_kennel(
        "stated",
        "elsewhere",
        "pub fn seated() -> std::path::PathBuf {\n    std::env::temp_dir()\n}\n",
    );

    assert!(
        !lure.bktu_root().join("clippy.toml").exists(),
        "the crate root must hold no list, or this hurdle proves nothing"
    );

    match zbktz_lint(&lure) {
        bkcz_Verdict::Refused(_) => (),
        other => panic!("the collar's own muzzle directory should govern: {:?}", other),
    }
}

/// THE CAP OUTRANKS `deny(warnings)`, which is the whole trick and the one
/// hazard: without it, driving the linter at all would promote its entire corpus
/// to hard errors under a crate that denies warnings, and every crate would
/// refuse for reasons no muzzle names.
///
/// The planted warning is an ordinary one the muzzle says nothing about, under a
/// crate attribute that would make it fatal.
#[test]
fn bktz_the_cap_outranks_a_crate_that_denies_warnings() {
    let lure = zbktz_kennel(
        "capped",
        ".",
        "#![deny(warnings)]\npub fn seated() -> u32 {\n    let unread = 7;\n    9\n}\n",
    );

    assert!(
        matches!(zbktz_lint(&lure), bkcz_Verdict::Clean(_)),
        "a lint the muzzle does not name must not decide this door's verdict"
    );
}

/// A CRATE THAT DOES NOT COMPILE IS NOT A MUZZLE FINDING, and the door says so
/// rather than reporting a refusal about calls it never got to read.
#[test]
fn bktz_a_crate_that_does_not_compile_is_told_apart() {
    let lure = zbktz_kennel("unbuilt", ".", "pub fn seated() -> u32 {\n    \"not a number\"\n}\n");

    match zbktz_lint(&lure) {
        bkcz_Verdict::Unbuilt(_) => (),
        other => panic!("a build failure should be told apart from a refusal: {:?}", other),
    }
}

// eof
