# Google Cloud Build for Recipe Bottle RBIA (discrete-source; no referrer tools)

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: derive-tag-base
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        # Derive createTime -> TAG_BASE (UTC, compact)
        CT="$(gcloud builds describe "${BUILD_ID}" --format='value(createTime)')"
        test -n "${CT}" || (echo "createTime missing" >&2; exit 1)
        # Example: 2025-08-22T16:12:34.123456Z -> 20250822T161234Z
        TAG_BASE="$(printf '%s\n' "${CT}" | sed -E 's/[-:]//g; s/\.[0-9]+Z$/Z/; s/\+.*$//')"
        test -n "${TAG_BASE}" || (echo "TAG_BASE empty" >&2; exit 1)
        echo "${TAG_BASE}" > .tag_base

  - name: gcr.io/cloud-builders/gcloud
    id: auth-docker-to-gar
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud auth configure-docker "${_RBGY_GAR_LOCATION}-docker.pkg.dev" --quiet

  - name: gcr.io/cloud-builders/docker
    id: buildx-create
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        docker buildx create --name rbia-builder --driver docker-container --use
        docker buildx inspect --bootstrap

  - name: gcr.io/cloud-builders/docker
    id: build-and-push
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        # Required inputs
        test -n "${_RBGY_DOCKERFILE}"     || (echo "_RBGY_DOCKERFILE missing"     >&2; exit 1)
        test -n "${_RBGY_MONIKER}"        || (echo "_RBGY_MONIKER missing"        >&2; exit 1)
        test -n "${_RBGY_PLATFORMS}"      || (echo "_RBGY_PLATFORMS missing"      >&2; exit 1)
        test -n "${_RBGY_GAR_LOCATION}"   || (echo "_RBGY_GAR_LOCATION missing"   >&2; exit 1)
        test -n "${_RBGY_GAR_PROJECT}"    || (echo "_RBGY_GAR_PROJECT missing"    >&2; exit 1)
        test -n "${_RBGY_GAR_REPOSITORY}" || (echo "_RBGY_GAR_REPOSITORY missing" >&2; exit 1)
        test -s .tag_base                  || (echo "tag base not derived"         >&2; exit 1)
        test -n "${_RBGY_GIT_COMMIT}"     || (echo "_RBGY_GIT_COMMIT missing"     >&2; exit 1)
        test -n "${_RBGY_GIT_BRANCH}"     || (echo "_RBGY_GIT_BRANCH missing"     >&2; exit 1)
        test -n "${_RBGY_GIT_REPO}"       || (echo "_RBGY_GIT_REPO missing"       >&2; exit 1)

        TAG_BASE="$(cat .tag_base)"
        IMAGE_URI="${_RBGY_GAR_LOCATION}-docker.pkg.dev/${_RBGY_GAR_PROJECT}/${_RBGY_GAR_REPOSITORY}/${_RBGY_MONIKER}:${TAG_BASE}-img"

        : > build.log
        run() { echo "\$ $* " >> build.log; "$@" >> build.log 2>&1; }

        run docker buildx version
        run docker version
        run docker info

        run docker buildx build \
          --platform="${_RBGY_PLATFORMS}" \
          --tag "${IMAGE_URI}" \
          --push \
          --label "moniker=${_RBGY_MONIKER}" \
          --label "git.commit=${_RBGY_GIT_COMMIT}" \
          --label "git.branch=${_RBGY_GIT_BRANCH}" \
          -f "${_RBGY_DOCKERFILE}" \
          .

        echo "${IMAGE_URI}" > .image_uri

  - name: "${_RBGY_JQ_REF}"
    id: assemble-metadata
    entrypoint: sh
    args:
      - -c
      - |
        set -euo pipefail
        test -s .tag_base || (echo "tag base not derived" >&2; exit 1)
        TAG_BASE="$(cat .tag_base)"
        IMG_URI="$(cat .image_uri)"
        cp "${_RBGY_DOCKERFILE}" recipe.txt
        TS="$(date -u +%FT%TZ)"
        jq -n                                    \
          --arg tag_base  "${TAG_BASE}"          \
          --arg image_uri "${IMG_URI}"           \
          --arg moniker   "${_RBGY_MONIKER}"     \
          --arg repo      "${_RBGY_GIT_REPO}"    \
          --arg branch    "${_RBGY_GIT_BRANCH}"  \
          --arg commit    "${_RBGY_GIT_COMMIT}"  \
          --arg ts        "${TS}"                \
          --arg platforms "${_RBGY_PLATFORMS}"   \
          '{
            tag_base: $tag_base,
            image: { uri: $image_uri },
            moniker: $moniker,
            git: { repo: $repo, branch: $branch, commit: $commit },
            build: { timestamp: $ts },
            platforms: $platforms
          }' > build_info.json

  - name: gcr.io/cloud-builders/docker
    id: sbom-and-summary
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        test -n "${_RBGY_SYFT_REF}" || (echo "_RBGY_SYFT_REF missing" >&2; exit 1)
        IMAGE_URI="$(cat .image_uri)"
        docker run --rm "${_RBGY_SYFT_REF}" "${IMAGE_URI}" -o json  > syft_analysis.json
        docker run --rm "${_RBGY_SYFT_REF}" "${IMAGE_URI}" -o table > package_summary.txt

  - name: gcr.io/cloud-builders/docker
    id: build-and-push-metadata
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        test -s .tag_base || (echo "tag base not derived" >&2; exit 1)
        TAG_BASE="$(cat .tag_base)"
        META_URI="${_RBGY_GAR_LOCATION}-docker.pkg.dev/${_RBGY_GAR_PROJECT}/${_RBGY_GAR_REPOSITORY}/${_RBGY_MONIKER}:${TAG_BASE}-meta"

        {
          echo 'FROM scratch'
          echo 'LABEL org.opencontainers.image.title="rbia-metadata"'
          echo 'ADD build_info.json /build_info.json'
          echo 'ADD syft_analysis.json /syft_analysis.json'
          echo 'ADD package_summary.txt /package_summary.txt'
          echo 'ADD recipe.txt /recipe.txt'
        } > Dockerfile.meta

        docker build -f Dockerfile.meta -t "${META_URI}" .
        docker push "${META_URI}"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "${_RBGY_MACHINE_TYPE}"

timeout: "${_RBGY_TIMEOUT}"

substitutions:
  _RBGY_DOCKERFILE: Dockerfile
  _RBGY_MONIKER: rbia
  _RBGY_PLATFORMS: linux/amd64
  _RBGY_GAR_LOCATION: us-central1
  _RBGY_GAR_PROJECT: your-project-id
  _RBGY_GAR_REPOSITORY: your-repo
  _RBGY_GIT_COMMIT: unknown
  _RBGY_GIT_BRANCH: unknown
  _RBGY_GIT_REPO: unknown
  _RBGY_MACHINE_TYPE: E2_HIGHCPU_8
  _RBGY_TIMEOUT: 1200s
  _RBGY_JQ_REF: ""
  _RBGY_SYFT_REF: ""
