steps:
  - name: gcr.io/cloud-builders/gcloud
    id: auth-docker-to-gar
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud auth configure-docker "${_RBGY_GAR_LOCATION}-docker.pkg.dev" --quiet

  - name: gcr.io/go-containerregistry/gcrane
    id: copy
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -eu
        SRC="${_SRC_IMAGE}"   # e.g. docker.io/library/busybox:1.37
        DEST="${_RBGY_GAR_LOCATION}-docker.pkg.dev/${_RBGY_GAR_PROJECT}/${_RBGY_GAR_REPOSITORY}/${_DEST_PATH}:${_DEST_TAG}"
        # For private sources you can: gcrane auth login docker.io -u "$DOCKER_USER" -p "$DOCKER_PASS"
        gcrane cp "${SRC}" "${DEST}"
        echo "${DEST}" > copied.txt

  - name: gcr.io/cloud-builders/gcloud
    id: note
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        echo "Copied to: $(cat copied.txt)"

options:
  machineType: "${_RBGY_MACHINE_TYPE}"
  logging: CLOUD_LOGGING_ONLY
timeout: "${_RBGY_TIMEOUT}"

substitutions:
  # GAR target (fed from RBRR)
  _RBGY_GAR_LOCATION: us-central1
  _RBGY_GAR_PROJECT: your-project-id
  _RBGY_GAR_REPOSITORY: your-repo

  # Copy operation specifics
  _DEST_PATH: imported/busybox
  _DEST_TAG: 1.37
  _SRC_IMAGE: docker.io/library/busybox:1.37

  # Build options (API-native)
  _RBGY_MACHINE_TYPE: E2_HIGHCPU_8
  _RBGY_TIMEOUT: 600s

