# Google Cloud Build for Recipe Bottle RBIA
#
# Policy:
# - Build & push use Google-curated builders.
# - Third-party containers (jq, syft, gcrane, oras) run ONLY AFTER the image is created and pushed.
# - No binfmt or GCS usage.

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: auth-docker-to-gar
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud auth configure-docker "${_RBGY_GAR_LOCATION}-docker.pkg.dev" --quiet

  - name: gcr.io/cloud-builders/docker
    id: buildx-create
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        docker buildx create --name rbia-builder --driver docker-container --use
        docker buildx inspect --bootstrap

  - name: gcr.io/cloud-builders/docker
    id: build-and-push
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        # One-var-per-line checks
        test -n "${_RBGY_DOCKERFILE}"     || (echo "_RBGY_DOCKERFILE missing"     >&2; exit 1)
        test -n "${_RBGY_TAG}"            || (echo "_RBGY_TAG missing"            >&2; exit 1)
        test -n "${_RBGY_MONIKER}"        || (echo "_RBGY_MONIKER missing"        >&2; exit 1)
        test -n "${_RBGY_PLATFORMS}"      || (echo "_RBGY_PLATFORMS missing"      >&2; exit 1)
        test -n "${_RBGY_GAR_LOCATION}"   || (echo "_RBGY_GAR_LOCATION missing"   >&2; exit 1)
        test -n "${_RBGY_GAR_PROJECT}"    || (echo "_RBGY_GAR_PROJECT missing"    >&2; exit 1)
        test -n "${_RBGY_GAR_REPOSITORY}" || (echo "_RBGY_GAR_REPOSITORY missing" >&2; exit 1)
        test -n "${_RBGY_GIT_COMMIT}"     || (echo "_RBGY_GIT_COMMIT missing"     >&2; exit 1)
        test -n "${_RBGY_GIT_BRANCH}"     || (echo "_RBGY_GIT_BRANCH missing"     >&2; exit 1)
        test -n "${_RBGY_GIT_REPO}"       || (echo "_RBGY_GIT_REPO missing"       >&2; exit 1)

        IMAGE_URI="${_RBGY_GAR_LOCATION}-docker.pkg.dev/${_RBGY_GAR_PROJECT}/${_RBGY_GAR_REPOSITORY}/${_RBGY_MONIKER}:${_RBGY_TAG}"

        : > build.log
        run() { echo "\$ $* " >> build.log; "$@" >> build.log 2>&1; }

        run docker buildx version
        run docker version
        run docker info

        run docker buildx build \
          --platform="${_RBGY_PLATFORMS}" \
          --tag "${IMAGE_URI}" \
          --push \
          --label "moniker=${_RBGY_MONIKER}" \
          --label "git.commit=${_RBGY_GIT_COMMIT}" \
          --label "git.branch=${_RBGY_GIT_BRANCH}" \
          -f "${_RBGY_DOCKERFILE}" \
          .

        echo "${IMAGE_URI}" > .image_uri

  # METADATA (POST-BUILD): assemble build_info.json with jq
  - name: "${_RBGY_JQ_REF}"
    id: assemble-metadata
    entrypoint: sh
    args:
      - -c
      - |
        set -euo pipefail
        test -n "${_RBGY_TAG}"        || (echo "_RBGY_TAG missing"        >&2; exit 1)
        test -n "${_RBGY_MONIKER}"    || (echo "_RBGY_MONIKER missing"    >&2; exit 1)
        test -n "${_RBGY_GIT_COMMIT}" || (echo "_RBGY_GIT_COMMIT missing" >&2; exit 1)
        test -n "${_RBGY_GIT_BRANCH}" || (echo "_RBGY_GIT_BRANCH missing" >&2; exit 1)
        test -n "${_RBGY_GIT_REPO}"   || (echo "_RBGY_GIT_REPO missing"   >&2; exit 1)

        cp "${_RBGY_DOCKERFILE}" recipe.txt
        TS="$(date -u +%FT%TZ)"
        jq -n                                    \
          --arg tag       "${_RBGY_TAG}"         \
          --arg moniker   "${_RBGY_MONIKER}"     \
          --arg repo      "${_RBGY_GIT_REPO}"    \
          --arg branch    "${_RBGY_GIT_BRANCH}"  \
          --arg commit    "${_RBGY_GIT_COMMIT}"  \
          --arg ts        "${TS}"                \
          --arg platforms "${_RBGY_PLATFORMS}"   \
          '{
            tag: $tag,
            moniker: $moniker,
            git: { repo: $repo, branch: $branch, commit: $commit },
            build: { timestamp: $ts },
            platforms: $platforms
          }' > build_info.json

  # SBOM (POST-BUILD)
  - name: gcr.io/cloud-builders/docker
    id: sbom-and-summary
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        test -n "${_RBGY_SYFT_REF}" || (echo "_RBGY_SYFT_REF missing" >&2; exit 1)
        IMAGE_URI="$(cat .image_uri)"
        docker run --rm "${_RBGY_SYFT_REF}" "${IMAGE_URI}" -o json  > syft_analysis.json
        docker run --rm "${_RBGY_SYFT_REF}" "${IMAGE_URI}" -o table > package_summary.txt

  # Resolve the pushed image DIGEST (for referrers)
  - name: "${_RBGY_GCRANE_REF}"
    id: resolve-digest
    entrypoint: sh
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE_URI="$(cat .image_uri)"
        gcrane digest "${IMAGE_URI}" > .image_digest
        echo "Resolved digest: $(cat .image_digest)"

  # Attach metadata & SBOM as OCI referrers in the SAME GAR repo
  - name: "${_RBGY_ORAS_REF}"
    id: attach-referrers
    entrypoint: sh
    args:
      - -c
      - |
        set -euo pipefail
        test -s .image_digest || (echo "missing image digest" >&2; exit 1)
        IMAGE_DIGEST="$(cat .image_digest)"
        SUBJECT="${_RBGY_GAR_LOCATION}-docker.pkg.dev/${_RBGY_GAR_PROJECT}/${_RBGY_GAR_REPOSITORY}/${_RBGY_MONIKER}@${IMAGE_DIGEST}"

        # Attach build_info.json
        oras attach "${SUBJECT}" build_info.json \
          --artifact-type "application/vnd.recipemuster.build-info+json" \
          --annotation "org.opencontainers.image.title=build_info.json"

        # Attach SBOM (Syft)
        oras attach "${SUBJECT}" syft_analysis.json \
          --artifact-type "application/vnd.syft+json" \
          --annotation "org.opencontainers.image.title=syft_analysis.json"

        # (Optional) attach the human-readable package summary
        oras attach "${SUBJECT}" package_summary.txt \
          --artifact-type "text/plain" \
          --annotation "org.opencontainers.image.title=package_summary.txt"

options:
  machineType: "${_RBGY_MACHINE_TYPE}"
  logging: CLOUD_LOGGING_ONLY
timeout: "${_RBGY_TIMEOUT}"

timeout: ${_RBGY_TIMEOUT}

substitutions:
  # Required inputs
  _RBGY_DOCKERFILE: Dockerfile
  _RBGY_TAG: dev
  _RBGY_MONIKER: rbia
  _RBGY_PLATFORMS: linux/amd64
  _RBGY_GAR_LOCATION: us-central1
  _RBGY_GAR_PROJECT: your-project-id
  _RBGY_GAR_REPOSITORY: your-repo
  _RBGY_GIT_COMMIT: unknown
  _RBGY_GIT_BRANCH: unknown
  _RBGY_GIT_REPO: unknown
  _RBGY_MACHINE_TYPE: E2_HIGHCPU_8
  _RBGY_TIMEOUT: 1200s

  # Post-build tool pins (values provided by rbf_submit_build)
  _RBGY_JQ_REF: ""
  _RBGY_SYFT_REF: ""
  _RBGY_GCRANE_REF: ""
  _RBGY_ORAS_REF: ""

