# Google Cloud Build configuration for Recipe Bottle images
# Expects substitutions: RBIA_DOCKERFILE, RBIA_TAG, RBIA_MONIKER, RBIA_PLATFORMS, RBIA_GAR_LOCATION, RBIA_GAR_PROJECT, RBIA_GAR_REPOSITORY

steps:
  # Build and push multi-platform image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-push'
    args:
      - 'buildx'
      - 'build'
      - '--push'
      - '--platform=${RBIA_PLATFORMS}'
      - '--tag=${RBIA_GAR_LOCATION}-docker.pkg.dev/${RBIA_GAR_PROJECT}/${RBIA_GAR_REPOSITORY}/${RBIA_TAG}'
      - '--label=moniker=${RBIA_MONIKER}'
      - '--label=git.commit=${RBIA_GIT_COMMIT}'
      - '--label=git.branch=${RBIA_GIT_BRANCH}'
      - '--label=git.repo=${RBIA_GIT_REPO}'
      - '--label=recipe=${RBIA_RECIPE_NAME}'
      - '--file=${RBIA_DOCKERFILE}'
      - '.'

  # Pull image for analysis
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-for-analysis'
    args:
      - 'pull'
      - '${RBIA_GAR_LOCATION}-docker.pkg.dev/${RBIA_GAR_PROJECT}/${RBIA_GAR_REPOSITORY}/${RBIA_TAG}'

  # Run Syft analysis
  - name: 'anchore/syft:v1.14.1'
    id: 'syft-analysis'
    args:
      - '${RBIA_GAR_LOCATION}-docker.pkg.dev/${RBIA_GAR_PROJECT}/${RBIA_GAR_REPOSITORY}/${RBIA_TAG}'
      - '-o'
      - 'json=/workspace/syft_analysis.json'

  # Create metadata archive
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-metadata'
    script: |
      #!/bin/bash
      set -euo pipefail

      # Create metadata directory
      mkdir -p /workspace/metadata

      # Copy artifacts
      cp ${RBIA_DOCKERFILE} /workspace/metadata/recipe.txt
      cp /workspace/syft_analysis.json /workspace/metadata/

      # Create build info
      cat > /workspace/metadata/build_info.json <<EOF
      {
        "tag": "${RBIA_TAG}",
        "moniker": "${RBIA_MONIKER}",
        "git_commit": "${RBIA_GIT_COMMIT}",
        "git_branch": "${RBIA_GIT_BRANCH}",
        "git_repo": "${RBIA_GIT_REPO}",
        "build_id": "${BUILD_ID}",
        "build_timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
        "platforms": "${RBIA_PLATFORMS}"
      }
      EOF

      # Create package summary from Syft
      jq -r '.artifacts[] | "\(.name) \(.version)"' /workspace/syft_analysis.json | \
        sort | uniq -c | sort -rn | head -n 20 > /workspace/metadata/package_summary.txt

      # Archive metadata
      tar -czf /workspace/${RBIA_TAG}_metadata.tar.gz -C /workspace/metadata .

  # Upload metadata as generic artifact
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'upload-metadata'
    args:
      - 'artifacts'
      - 'generic'
      - 'upload'
      - '--location=${RBIA_GAR_LOCATION}'
      - '--repository=${RBIA_GAR_REPOSITORY}'
      - '--project=${RBIA_GAR_PROJECT}'
      - '--package=${RBIA_TAG}'
      - '--version=metadata'
      - '--source=/workspace/${RBIA_TAG}_metadata.tar.gz'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'GCS_ONLY'

timeout: '1200s'

