// Copyright 2026 Scale Invariant, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The selection pipeline, proven over a lure by a SPAWNED kennel.
//!
//! WHY THESE HURDLES CANNOT STAND IN THE LIB. Every claim here is about what a
//! door DID — which hurdles a run actually ran, that a refusal spawned no runner
//! at all, that a listing door listed and stopped. None of that is observable
//! from inside the library, whose functions compose invocations and never take
//! an exit; the observation is of a child process's streams and its code, so the
//! seat is the integration one, and the kennel judged is the binary cargo just
//! built (`CARGO_BIN_EXE_bkx`).
//!
//! THE LISTING IS CAPTURED IN THE SAME HURDLE AS THE RUN IT NARROWS. A run
//! asserted against a listing taken elsewhere would be asserted against a
//! different compile of a different tree; taking both over one lure in one
//! hurdle is what makes "exactly the two that matched" a claim about this suite
//! rather than about a remembered one.

#![deny(warnings)]

#[path = "../src/bktu_lure.rs"]
#[allow(dead_code, non_camel_case_types)]
mod bktu_lure;

use bktu_lure::bktu_Lure;
use std::ffi::OsStr;
use std::path::Path;
use std::process::Output;

/// The exit the kennel takes when a pattern set matches nothing.
///
/// SPELLED HERE BECAUSE THE BAND MAKES IT AN ASSERTION AND NOT AN INTERNAL. A
/// door's refusal codes are declared private to the binary, and the drive hurdle
/// beside this one deliberately asserts only non-zero for that reason — but this
/// code is the one the pipeline's contract NAMES: a caller distinguishes "your
/// patterns matched nothing" from every other refusal by reading it, so a hurdle
/// that accepted any non-zero would not be proving the contract at all.
const ZBKTI_EXIT_EMPTY_MATCH: i32 = 75;

/// The kennel this drive judges: the binary cargo just built.
fn zbkti_kennel() -> &'static Path {
    Path::new(env!("CARGO_BIN_EXE_bkx"))
}

/// A lure holding a crate with FOUR hurdles across two modules, and a suite
/// collar over it under cargo's own harness.
///
/// FOUR RATHER THAN TWO, and the two modules are load-bearing: a pattern that
/// selects two of four out of one module proves a narrowing; the same pattern
/// against a suite of two would be indistinguishable from a run of everything,
/// which is exactly the failure an empty selection produces.
fn zbkti_lure(name: &str) -> bktu_Lure {
    let lure = bktu_Lure::bktu_compose(name);

    lure.bktu_write(
        "Cargo.toml",
        "[package]\nname = \"lure\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
         [lib]\nname = \"lure\"\npath = \"src/lib.rs\"\n",
    );
    lure.bktu_write(
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\nname = \"lure\"\nversion = \"0.0.1\"\n",
    );
    lure.bktu_write(
        "src/lib.rs",
        "#[cfg(test)]\nmod alpha {\n\
         \x20   #[test]\n    fn one() {}\n\
         \x20   #[test]\n    fn two() {}\n}\n\
         #[cfg(test)]\nmod beta {\n\
         \x20   #[test]\n    fn three() {}\n\
         \x20   #[test]\n    fn four() {}\n}\n",
    );
    lure.bktu_write("clippy.toml", "# the lure's muzzle\n");

    // THE BUILD DIRECTORY IS IGNORED, as it is in every repository a collar
    // really stands in. Without it this lure is a ONE-DRIVE lure: the first
    // door to run a compiler leaves `target/` untracked, and the door law
    // refuses every drive after it — which is the shape a hurdle taking a
    // listing AND then the run it narrows cannot live with.
    lure.bktu_write(".gitignore", "target/\n");
    lure.bktu_write(
        "suite-lure/bkrr.env",
        "BKRR_COLLAR=\"suite-lure\"\n\
         BKRR_KIND=\"bknre_suite\"\n\
         BKRR_MANIFEST=\"Cargo.toml\"\n\
         BKRR_TARGET=\"bknre_manifest\"\n\
         BKRR_ROOTS=\"src Cargo.toml\"\n\
         BKRR_FEATURES=\"\"\n\
         BKRR_PROFILE=\"test\"\n\
         BKRR_SPEND=\"bknre_reader\"\n\
         BKRR_TAMED_CRATES=\"\"\n\
         BKRR_FERAL_CRATES=\"bknre_tamed\"\n\
         BKRR_MUZZLE=\".\"\nBKRR_EXERGUE=\"bknre_unstruck\"\n\
         BKRR_RUNNER=\"bknre_cargo\"\n\
         BKRR_TONGUE=\"bknre_harness\"\n",
    );
    lure.bktu_commit("stand the suite up");

    lure
}

/// Everything the kennel said on a drive, both streams as one string.
///
/// The door writes its voice and its diagnostics to two streams, so a claim
/// about a narrowing has to read both; joining them is how this hurdle asks
/// "what did the operator see".
fn zbkti_said(out: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    )
}

fn zbkti_drive(lure: &bktu_Lure, args: &[&str]) -> Output {
    zbkti_drive_at(lure, args, "0")
}

/// Drive with the substrate's verbosity dial set.
///
/// THE DIAL IS A PARAMETER HERE BECAUSE THE TWO CLAIMS WANT DIFFERENT FLAVORS.
/// How MANY hurdles ran is the verdict, which the quiet flavor states; WHICH
/// ones ran is per-case reporting, which is the verbose flavor's — the bounded
/// voice renders the runner's stream rather than passing it through, so a
/// hurdle asserting a case name at the quiet flavor would be asserting against
/// output nobody promised it.
///
/// THE SPAWN IS THE COMPOSING SURFACE'S, and this seat reaches it there rather
/// than composing a child of its own — which it did until a door began banking a
/// fact file and this file's green drives wrote their measurements into the
/// directories of the run executing them. A second `Command` is what the
/// surface's only-home rule exists to prevent, and the cost of one is exactly
/// this: a seat the surface composes for every drive is a seat the second spawn
/// does not get.
fn zbkti_drive_at(lure: &bktu_Lure, args: &[&str], dial: &str) -> Output {
    lure.bktu_drive_stating(
        zbkti_kennel(),
        args,
        &[(bkk::bkco_output::BKCO_VERBOSE_VAR, OsStr::new(dial))],
    )
}

/// The voice's verdict line for a green run of `ran` cases.
///
/// COMPOSED RATHER THAN SPELLED, so a hurdle asserting the narrowing is
/// asserting the shape the voice actually renders and not a second copy of it
/// free to drift.
fn zbkti_green(ran: usize) -> String {
    format!("green: {} ran, {} passed, 0 failed", ran, ran)
}

#[test]
fn bkti_a_pattern_runs_exactly_the_hurdles_it_matched() {
    let lure = zbkti_lure("selection-narrows");

    // THE LISTING, TAKEN IN THIS HURDLE, over this lure and this compile. The
    // run below is asserted against THIS, never against a remembered suite.
    let listed = zbkti_drive(&lure, &["lineup", "suite-lure"]);
    assert!(listed.status.success(), "the listing lands: {}", zbkti_said(&listed));
    let listing = String::from_utf8_lossy(&listed.stdout);
    let held: Vec<&str> = listing.lines().filter(|line| !line.trim().is_empty()).collect();
    assert_eq!(held.len(), 4, "the lure's suite holds four hurdles: {:?}", held);
    assert!(held.iter().any(|hurdle| hurdle.ends_with("alpha::one")));
    assert!(held.iter().any(|hurdle| hurdle.ends_with("beta::three")));

    // AT THE VERBOSE FLAVOR, because this hurdle asserts WHICH hurdles ran and
    // per-case reporting is what that flavor is for.
    let ran = zbkti_drive_at(&lure, &["mush", "suite-lure", "^alpha::"], "1");
    let said = zbkti_said(&ran);

    assert!(ran.status.success(), "the narrowed run lands: {}", said);

    // THE VERDICT NAMES THE NARROWING, and the count on its right is the one the
    // listing above reported rather than a number this hurdle knows some other
    // way.
    assert!(
        said.contains(&format!("ran 2 of {}", held.len())),
        "the verdict names the narrowing: {}",
        said
    );

    // AND THE RUN IS THE NARROWING, observed in the door's own verdict and its
    // per-case reporting: the two matched hurdles ran and the two that did not
    // match were never handed to the runner at all.
    assert!(said.contains(&zbkti_green(2)), "exactly two ran: {}", said);
    assert!(said.contains("alpha::one"), "the matched hurdles ran: {}", said);
    assert!(said.contains("alpha::two"), "the matched hurdles ran: {}", said);
    assert!(
        !said.contains("beta::three"),
        "an unmatched hurdle did not run: {}",
        said
    );
}

#[test]
fn bkti_a_pattern_set_matching_nothing_refuses_and_spawns_no_runner() {
    let lure = zbkti_lure("selection-empty");

    let out = zbkti_drive(&lure, &["mush", "suite-lure", "gamma"]);
    let said = zbkti_said(&out);

    assert_eq!(
        out.status.code(),
        Some(ZBKTI_EXIT_EMPTY_MATCH),
        "the refusal takes its named code from the band: {}",
        said
    );

    // NO RUNNER WAS SPAWNED, proven from the transcript rather than asserted: a
    // cargo test run says so on its own stream, and none of it is here. This is
    // the claim that matters — cargo's harness reports a filter matching nothing
    // as a PASS, so a kennel that handed the selection through would have
    // produced a green for a suite it never ran.
    assert!(!said.contains("green:"), "no runner reported: {}", said);
    assert!(!said.contains("RED"), "no runner reported: {}", said);
    assert!(!said.contains(" ran, "), "no runner reported: {}", said);
    assert!(
        said.contains("NOTHING WAS SPAWNED"),
        "the refusal says what it did not do: {}",
        said
    );
}

#[test]
fn bkti_the_bare_drive_is_the_whole_suite_and_asks_for_no_listing() {
    let lure = zbkti_lure("selection-bare");

    // AT THE DIAGNOSTIC FLAVOR, because the claim below is about the INVOCATION
    // the door composed, which is the kennel's own diagnostic rather than its
    // voice.
    let out = zbkti_drive_at(&lure, &["mush", "suite-lure"], "2");
    let said = zbkti_said(&out);

    assert!(out.status.success(), "the bare drive lands: {}", said);
    assert!(said.contains(&zbkti_green(4)), "the whole suite ran: {}", said);

    // THE PIPELINE IS WHAT A NARROWING COSTS, and a bare drive does not pay it.
    // The verdict line a bare drive prints is the one it printed before this
    // pipeline existed, and no narrowing is announced over it.
    assert!(
        !said.contains("narrows:"),
        "a bare drive announces no narrowing: {}",
        said
    );
    assert!(
        !said.contains("--exact"),
        "a bare drive spells no selection: {}",
        said
    );
    assert!(
        said.contains("runs its suite: test --profile test"),
        "the bare drive's verdict line stands unchanged: {}",
        said
    );
}

#[test]
fn bkti_lineup_lists_and_runs_nothing() {
    let lure = zbkti_lure("selection-lineup");

    let out = zbkti_drive(&lure, &["lineup", "suite-lure"]);
    let said = zbkti_said(&out);

    assert!(out.status.success(), "the listing door lands: {}", said);
    assert!(said.contains("alpha::one"), "it names the hurdles: {}", said);
    assert!(said.contains("holds 4 hurdle(s)"), "it counts them: {}", said);

    // THE NO-RUN, PROVEN BY THE TRANSCRIPT. A door that listed and then ran
    // would say so on the runner's own stream, in the two sentences a harness
    // always prints; neither is here.
    assert!(!said.contains("green:"), "nothing ran: {}", said);
    assert!(!said.contains("RED"), "nothing ran: {}", said);
    assert!(!said.contains(" ran, "), "nothing ran: {}", said);
}

#[test]
fn bkti_lineup_takes_a_collar_and_no_pattern() {
    let lure = zbkti_lure("selection-lineup-arity");

    // A pattern handed to the listing door would make it a dry run rather than a
    // listing, so the door refuses the shape rather than quietly ignoring the
    // word.
    let out = zbkti_drive(&lure, &["lineup", "suite-lure", "alpha"]);

    assert!(!out.status.success(), "the door refuses a second word");
}

/// A NARROWED GREEN COURSE RECORDS ITS NARROWING AND NO TIME, which is the half
/// of the record's rule no whole course can prove.
///
/// THIS SEAT IS WHERE THE PROOF BELONGS because it is the only one that narrows
/// a course through the door. Wall time is recorded only where a course ran
/// whole — a narrowed course's time is not the course's, and one such number
/// poisons the series it would be read against — so what the field carries here
/// is the token that says why there is no number.
///
/// THE HELD COUNT IS THE LISTING'S, not the run's: the patterns cut two hurdles
/// out of the four the suite holds, and a record that reported two out of two
/// would have lost exactly the fact a narrowing is read against.
#[test]
fn bkti_a_narrowed_green_course_records_its_narrowing_and_no_time() {
    let lure = zbkti_lure("selection-record");

    let out = zbkti_drive(&lure, &["mush", "suite-lure", "^alpha::"]);
    assert!(out.status.success(), "the narrowed run lands: {}", zbkti_said(&out));

    let leaf = format!("suite-lure.{}", bkk::bkcc_record::BKCC_EXTENSION);
    let banked = lure.bktu_output().join(&leaf);

    let said = std::fs::read_to_string(&banked)
        .unwrap_or_else(|err| panic!("the record stands at {}: {}", banked.display(), err));

    let read = bkk::bkcc_record::bkcc_admit(&said, &leaf)
        .unwrap_or_else(|err| panic!("the door's own record admits: {}", err));

    assert_eq!(
        read.narrowing.as_deref(),
        Some(&["alpha::one".to_string(), "alpha::two".to_string()][..]),
        "the record names the hurdles the patterns chose: {}",
        said
    );
    assert_eq!(read.driven, 2, "two hurdles ran: {}", said);
    assert_eq!(read.passed, 2, "and both passed: {}", said);
    assert_eq!(read.held, 4, "out of the four the suite holds: {}", said);
    assert!(read.wall.is_none(), "a narrowed course takes no time: {}", said);
}

// eof
