name: Build and Push Multiple Containers with Metrics

on:
  # I've disabled all triggers while I figure out how I want to go forward here
  #
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - dockerfile: Study/study-basic-container-registry-cycle/Dockerfile
            image: ghcr.io/bhyslop/recipemuster:hello-world-v1
          # Add more Dockerfile entries as needed, for example:
          # - dockerfile: path/to/another/Dockerfile
          #   image: ghcr.io/bhyslop/recipemuster:another-image

    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Calculate Dockerfile hash
      id: dockerfile-hash
      run: echo "::set-output name=hash::$(md5sum ${{ matrix.dockerfile }} | awk '{ print $1 }')"

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ steps.dockerfile-hash.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.image }}-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get start time
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}
        file: ${{ matrix.dockerfile }}
        push: false
        load: true
        tags: ${{ matrix.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Get end time and calculate duration
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "Build duration: $DURATION seconds"
        echo "BUILD_DURATION=$DURATION" >> $GITHUB_ENV

    - name: Check image size
      run: |
        IMAGE_SIZE=$(docker image inspect ${{ matrix.image }} --format='{{.Size}}')
        IMAGE_SIZE_MB=$((IMAGE_SIZE / 1024 / 1024))
        echo "Image size: $IMAGE_SIZE_MB MB"
        echo "IMAGE_SIZE=$IMAGE_SIZE_MB" >> $GITHUB_ENV

    - name: Check disk usage
      run: |
        DISK_USAGE=$(du -sh . | cut -f1)
        echo "Total disk usage: $DISK_USAGE"
        echo "DISK_USAGE=$DISK_USAGE" >> $GITHUB_ENV

    - name: Report metrics
      run: |
        echo "Image: ${{ matrix.image }}"
        echo "Build Duration: $BUILD_DURATION seconds"
        echo "Image Size: $IMAGE_SIZE MB"
        echo "Disk Usage: $DISK_USAGE"

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: docker push ${{ matrix.image }}

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
