name: RBGR Image Build Workflow

on:
  repository_dispatch:
    types: [rbgr_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build image and record history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RBG_RUNTIME: docker
        shell: bash
        run: |
          # Create unique temp directory in workspace
          export RBG_TEMP_DIR="${{ github.workspace }}/.rbg-temp-${{ github.run_id }}-${{ github.run_attempt }}"

          # Ensure it's completely empty
          rm -rf   "${RBG_TEMP_DIR}"
          mkdir -p "${RBG_TEMP_DIR}"

          # Generate build label once and use consistently
          DOCKERFILE="${{ github.event.client_payload.dockerfile }}"
          FULL_FILENAME=$(basename "$DOCKERFILE")
          FILENAME_WITHOUT_EXT="${FULL_FILENAME%.*}"
          export RBG_NOW_STAMP=$(date +'%Y%m%d__%H%M%S')
          BUILD_LABEL="${FILENAME_WITHOUT_EXT}.${RBG_NOW_STAMP}"

          ./Tools/rbgr_cli.sh rbgr_build_image "$DOCKERFILE" "$BUILD_LABEL"

          # Clean temp directory for next CLI call
          rm -rf   "${RBG_TEMP_DIR}"/*

          ./Tools/rbgr_cli.sh rbgr_record_history "$BUILD_LABEL"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

