name: RBGR Image Build Workflow

on:
  repository_dispatch:
    types: [rbgr_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        shell: bash
        run: |
          # Load configuration
          source ./mbv.variables.sh
          source ./rbrr.repo.sh

          # Export required environment
          echo "RBRR_BUILD_ARCHITECTURES=$RBRR_BUILD_ARCHITECTURES" >> $GITHUB_ENV
          echo "RBRR_HISTORY_DIR=$RBRR_HISTORY_DIR" >> $GITHUB_ENV
          echo "RBRR_REGISTRY_OWNER=$RBRR_REGISTRY_OWNER" >> $GITHUB_ENV
          echo "RBRR_REGISTRY_NAME=$RBRR_REGISTRY_NAME" >> $GITHUB_ENV
          echo "RBRR_REGISTRY=$RBRR_REGISTRY" >> $GITHUB_ENV
          echo "RBRR_GITHUB_PAT_ENV=$RBRR_GITHUB_PAT_ENV" >> $GITHUB_ENV
          echo "RBG_RUNTIME=docker" >> $GITHUB_ENV
          echo "RBG_TEMP_DIR=/tmp/rbgr_$$" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MBV_TOOLS_DIR=$MBV_TOOLS_DIR" >> $GITHUB_ENV

          # Create temp directory
          mkdir -p /tmp/rbgr_$$

      - name: Build image and record history
        shell: bash
        run: |
          # Extract build label from dockerfile path
          DOCKERFILE="${{ github.event.client_payload.dockerfile }}"
          FULL_FILENAME=$(basename "$DOCKERFILE")
          FILENAME_WITHOUT_EXT="${FULL_FILENAME%.*}"
          TIMESTAMP=$(date +'%Y%m%d__%H%M%S')
          BUILD_LABEL="${FILENAME_WITHOUT_EXT}.${TIMESTAMP}"

          # Run build
          ${{ env.MBV_TOOLS_DIR }}/rbgr_cli.sh build_image "$DOCKERFILE"

          # Record history
          ${{ env.MBV_TOOLS_DIR }}/rbgr_cli.sh record_history "$BUILD_LABEL"

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          rm -rf "${{ env.RBG_TEMP_DIR }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

