name: RBGR Image Delete Workflow

on:
  repository_dispatch:
    types: [rbgr_delete]

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        shell: bash
        run: |
          # Load configuration
          source ./mbv.variables.sh
          source ./rbrr.repo.sh

          # Export required environment
          echo "RBRR_BUILD_ARCHITECTURES=$RBRR_BUILD_ARCHITECTURES" >> $GITHUB_ENV
          echo "RBRR_HISTORY_DIR=$RBRR_HISTORY_DIR" >> $GITHUB_ENV
          echo "RBRR_REGISTRY_OWNER=$RBRR_REGISTRY_OWNER" >> $GITHUB_ENV
          echo "RBRR_REGISTRY_NAME=$RBRR_REGISTRY_NAME" >> $GITHUB_ENV
          echo "RBRR_REGISTRY=$RBRR_REGISTRY" >> $GITHUB_ENV
          echo "RBRR_GITHUB_PAT_ENV=$RBRR_GITHUB_PAT_ENV" >> $GITHUB_ENV
          echo "RBG_RUNTIME=docker" >> $GITHUB_ENV
          echo "RBG_TEMP_DIR=/tmp/rbgr_$$" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MBV_TOOLS_DIR=$MBV_TOOLS_DIR" >> $GITHUB_ENV

          # Create temp directory
          mkdir -p /tmp/rbgr_$$

      - name: Delete image and clean orphans
        shell: bash
        run: |
          # Delete image
          ${{ env.MBV_TOOLS_DIR }}/rbgr_cli.sh delete_image "${{ github.event.client_payload.fqin }}"

          # Clean orphans
          ${{ env.MBV_TOOLS_DIR }}/rbgr_cli.sh clean_orphans

          # Commit deletion history
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "${{ env.RBRR_HISTORY_DIR }}/_deletions"
          git commit -m "Record deletion of image" || echo "No deletion history to commit"
          git push || echo "No changes to push"

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          rm -rf "${{ env.RBG_TEMP_DIR }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

